-- ═══════════════════════════════════════════════════════════════
-- Catálogo ampliado: 1000 productos con marca, repartidos en 8
-- categorías (las 3 originales + 5 nuevas: Electrónica, Hogar,
-- Limpieza, Mascotas, Bazar). Generado programáticamente para
-- tener volumen realista de datos de prueba.
--
-- Idempotente: usa WHERE NOT EXISTS por nombre.
-- ═══════════════════════════════════════════════════════════════

INSERT INTO products (name, brand, description, category, created_at, updated_at)
SELECT v.name, v.brand, v.description, v.category, NOW(), NOW()
FROM (VALUES
  ('Caramelos Premium 250g', 'Matarazzo', 'Caramelos premium — línea Matarazzo', 'Alimento'),
  ('Miel Light 250g', 'Granix', 'Miel light — línea Granix', 'Alimento'),
  ('Mermelada Orgánico 300g', 'Ledesma', 'Mermelada orgánico — línea Ledesma', 'Alimento'),
  ('Manteca Light 400g', 'Terrabusi', 'Manteca light — línea Terrabusi', 'Alimento'),
  ('Margarina Orgánico 400g', 'Nucrem', 'Margarina orgánico — línea Nucrem', 'Alimento'),
  ('Ananá en Lata Clásico 400g', 'Ledesma', 'Ananá en Lata clásico — línea Ledesma', 'Alimento'),
  ('Harina Integral Premium 400g', 'Milkaut', 'Harina Integral premium — línea Milkaut', 'Alimento'),
  ('Polenta Premium 300g', 'Molto', 'Polenta premium — línea Molto', 'Alimento'),
  ('Ananá en Lata Light 250g', 'Bagley', 'Ananá en Lata light — línea Bagley', 'Alimento'),
  ('Papas Fritas Orgánico 200g', 'Granix', 'Papas Fritas orgánico — línea Granix', 'Alimento'),
  ('Puré de Tomate Clásico 400g', 'Cabaña', 'Puré de Tomate clásico — línea Cabaña', 'Alimento'),
  ('Maní Light 1kg', 'Granix', 'Maní light — línea Granix', 'Alimento'),
  ('Queso Cremoso Light 400g', 'Swift', 'Queso Cremoso light — línea Swift', 'Alimento'),
  ('Jamón Cocido Light 500g', 'Celusal', 'Jamón Cocido light — línea Celusal', 'Alimento'),
  ('Avena Clásico 200g', 'Marolio', 'Avena clásico — línea Marolio', 'Alimento'),
  ('Yerba Mate Orgánico 200g', 'Hellmann''s', 'Yerba Mate orgánico — línea Hellmann''s', 'Alimento'),
  ('Hamburguesas Premium 400g', 'Cañuelas', 'Hamburguesas premium — línea Cañuelas', 'Alimento'),
  ('Aceitunas Premium 1kg', 'Arcor', 'Aceitunas premium — línea Arcor', 'Alimento'),
  ('Queso Cremoso Clásico 1kg', 'Cabaña', 'Queso Cremoso clásico — línea Cabaña', 'Alimento'),
  ('Pan Rallado Clásico 300g', 'Cocinero', 'Pan Rallado clásico — línea Cocinero', 'Alimento'),
  ('Panqueques Premium 400g', 'Terrabusi', 'Panqueques premium — línea Terrabusi', 'Alimento'),
  ('Manteca Light 500g', 'Georgalos', 'Manteca light — línea Georgalos', 'Alimento'),
  ('Fideos Moñito Light 300g', 'Hellmann''s', 'Fideos Moñito light — línea Hellmann''s', 'Alimento'),
  ('Chicles Orgánico 1kg', 'Knorr', 'Chicles orgánico — línea Knorr', 'Alimento'),
  ('Manteca Tradicional 200g', 'Quaker', 'Manteca tradicional — línea Quaker', 'Alimento'),
  ('Jamón Cocido Premium 200g', 'Matarazzo', 'Jamón Cocido premium — línea Matarazzo', 'Alimento'),
  ('Chocolate en Barra Orgánico 1kg', 'Granix', 'Chocolate en Barra orgánico — línea Granix', 'Alimento'),
  ('Pan Rallado Light 500g', 'Cocinero', 'Pan Rallado light — línea Cocinero', 'Alimento'),
  ('Polenta Premium 250g', 'Paladini', 'Polenta premium — línea Paladini', 'Alimento'),
  ('Ketchup Premium 400g', 'Granix', 'Ketchup premium — línea Granix', 'Alimento'),
  ('Dulce de Leche Premium 500g', 'Molto', 'Dulce de Leche premium — línea Molto', 'Alimento'),
  ('Mermelada Premium 250g', 'Sancor', 'Mermelada premium — línea Sancor', 'Alimento'),
  ('Mostaza Orgánico 200g', 'Bagley', 'Mostaza orgánico — línea Bagley', 'Alimento'),
  ('Copos de Maíz Clásico 250g', 'Paladini', 'Copos de Maíz clásico — línea Paladini', 'Alimento'),
  ('Avena Premium 500g', 'Nucrem', 'Avena premium — línea Nucrem', 'Alimento'),
  ('Turrón Premium 200g', 'Marolio', 'Turrón premium — línea Marolio', 'Alimento'),
  ('Arvejas en Lata Premium 200g', 'Arcor', 'Arvejas en Lata premium — línea Arcor', 'Alimento'),
  ('Mermelada Tradicional 1kg', 'Matarazzo', 'Mermelada tradicional — línea Matarazzo', 'Alimento'),
  ('Duraznos en Almíbar Clásico 300g', 'Marolio', 'Duraznos en Almíbar clásico — línea Marolio', 'Alimento'),
  ('Hamburguesas Light 1kg', 'Cañuelas', 'Hamburguesas light — línea Cañuelas', 'Alimento'),
  ('Miel Premium 400g', 'Marolio', 'Miel premium — línea Marolio', 'Alimento'),
  ('Gelatina Light 200g', 'La Unión', 'Gelatina light — línea La Unión', 'Alimento'),
  ('Premezcla para Torta Orgánico 1kg', 'Bagley', 'Premezcla para Torta orgánico — línea Bagley', 'Alimento'),
  ('Yerba Mate Premium 300g', 'Arcor', 'Yerba Mate premium — línea Arcor', 'Alimento'),
  ('Aceitunas Tradicional 200g', 'La Campagnola', 'Aceitunas tradicional — línea La Campagnola', 'Alimento'),
  ('Papas Fritas Orgánico 500g', 'Paladini', 'Papas Fritas orgánico — línea Paladini', 'Alimento'),
  ('Miel Clásico 250g', 'Cocinero', 'Miel clásico — línea Cocinero', 'Alimento'),
  ('Mostaza Orgánico 400g', 'Matarazzo', 'Mostaza orgánico — línea Matarazzo', 'Alimento'),
  ('Lentejas Light 250g', 'Georgalos', 'Lentejas light — línea Georgalos', 'Alimento'),
  ('Caldo en Cubos Clásico 400g', 'Knorr', 'Caldo en Cubos clásico — línea Knorr', 'Alimento'),
  ('Ananá en Lata Premium 200g', 'Quaker', 'Ananá en Lata premium — línea Quaker', 'Alimento'),
  ('Gelatina Light 400g', 'Cabaña', 'Gelatina light — línea Cabaña', 'Alimento'),
  ('Garbanzos Clásico 300g', 'Ledesma', 'Garbanzos clásico — línea Ledesma', 'Alimento'),
  ('Harina Integral Light 250g', 'Knorr', 'Harina Integral light — línea Knorr', 'Alimento'),
  ('Avena Clásico 400g', 'Granix', 'Avena clásico — línea Granix', 'Alimento'),
  ('Turrón Orgánico 1kg', 'Swift', 'Turrón orgánico — línea Swift', 'Alimento'),
  ('Mermelada Premium 300g', 'Cocinero', 'Mermelada premium — línea Cocinero', 'Alimento'),
  ('Papas Fritas Clásico 250g', 'Ledesma', 'Papas Fritas clásico — línea Ledesma', 'Alimento'),
  ('Ketchup Light 250g', 'Quaker', 'Ketchup light — línea Quaker', 'Alimento'),
  ('Sopa Instantánea Orgánico 400g', 'Cocinero', 'Sopa Instantánea orgánico — línea Cocinero', 'Alimento'),
  ('Cereales Light 1kg', 'Marolio', 'Cereales light — línea Marolio', 'Alimento'),
  ('Caramelos Orgánico 1kg', 'La Campagnola', 'Caramelos orgánico — línea La Campagnola', 'Alimento'),
  ('Salchichas Clásico 300g', 'Celusal', 'Salchichas clásico — línea Celusal', 'Alimento'),
  ('Premezcla para Torta Tradicional 400g', 'Cabaña', 'Premezcla para Torta tradicional — línea Cabaña', 'Alimento'),
  ('Fideos Tirabuzón Light 300g', 'Sancor', 'Fideos Tirabuzón light — línea Sancor', 'Alimento'),
  ('Milanesas de Soja Tradicional 500g', 'Hellmann''s', 'Milanesas de Soja tradicional — línea Hellmann''s', 'Alimento'),
  ('Pan Lactal Clásico 300g', 'Cabaña', 'Pan Lactal clásico — línea Cabaña', 'Alimento'),
  ('Papas Fritas Tradicional 500g', 'La Campagnola', 'Papas Fritas tradicional — línea La Campagnola', 'Alimento'),
  ('Polenta Premium 200g', 'Molto', 'Polenta premium — línea Molto', 'Alimento'),
  ('Pan Lactal Light 300g', 'Granix', 'Pan Lactal light — línea Granix', 'Alimento'),
  ('Chicles Light 1kg', 'Cabaña', 'Chicles light — línea Cabaña', 'Alimento'),
  ('Postre Lácteo Clásico 1kg', 'Cabaña', 'Postre Lácteo clásico — línea Cabaña', 'Alimento'),
  ('Manteca Light 250g', 'Quaker', 'Manteca light — línea Quaker', 'Alimento'),
  ('Dulce de Leche Orgánico 1kg', 'Georgalos', 'Dulce de Leche orgánico — línea Georgalos', 'Alimento'),
  ('Arvejas en Lata Tradicional 200g', 'Quaker', 'Arvejas en Lata tradicional — línea Quaker', 'Alimento'),
  ('Yerba Mate Tradicional 400g', 'Granix', 'Yerba Mate tradicional — línea Granix', 'Alimento'),
  ('Dulce de Leche Orgánico 200g', 'Cabaña', 'Dulce de Leche orgánico — línea Cabaña', 'Alimento'),
  ('Vinagre Premium 1kg', 'Georgalos', 'Vinagre premium — línea Georgalos', 'Alimento'),
  ('Harina Integral Light 300g', 'Georgalos', 'Harina Integral light — línea Georgalos', 'Alimento'),
  ('Caldo en Cubos Tradicional 300g', 'Molto', 'Caldo en Cubos tradicional — línea Molto', 'Alimento'),
  ('Queso Cremoso Clásico 200g', 'Hellmann''s', 'Queso Cremoso clásico — línea Hellmann''s', 'Alimento'),
  ('Mermelada Light 300g', 'Marolio', 'Mermelada light — línea Marolio', 'Alimento'),
  ('Barritas de Cereal Clásico 200g', 'Matarazzo', 'Barritas de Cereal clásico — línea Matarazzo', 'Alimento'),
  ('Copos de Maíz Orgánico 400g', 'Marolio', 'Copos de Maíz orgánico — línea Marolio', 'Alimento'),
  ('Jamón Cocido Clásico 500g', 'Cocinero', 'Jamón Cocido clásico — línea Cocinero', 'Alimento'),
  ('Duraznos en Almíbar Tradicional 500g', 'Sancor', 'Duraznos en Almíbar tradicional — línea Sancor', 'Alimento'),
  ('Caramelos Clásico 500g', 'Quaker', 'Caramelos clásico — línea Quaker', 'Alimento'),
  ('Miel Light 500g', 'Matarazzo', 'Miel light — línea Matarazzo', 'Alimento'),
  ('Vinagre Clásico 250g', 'Quaker', 'Vinagre clásico — línea Quaker', 'Alimento'),
  ('Avena Light 500g', 'Knorr', 'Avena light — línea Knorr', 'Alimento'),
  ('Alfajor Orgánico 200g', 'Sancor', 'Alfajor orgánico — línea Sancor', 'Alimento'),
  ('Alfajor Clásico 200g', 'Matarazzo', 'Alfajor clásico — línea Matarazzo', 'Alimento'),
  ('Dulce de Leche Tradicional 1kg', 'Knorr', 'Dulce de Leche tradicional — línea Knorr', 'Alimento'),
  ('Pan Lactal Premium 500g', 'Cocinero', 'Pan Lactal premium — línea Cocinero', 'Alimento'),
  ('Aceitunas Clásico 200g', 'Celusal', 'Aceitunas clásico — línea Celusal', 'Alimento'),
  ('Aceitunas Clásico 400g', 'Swift', 'Aceitunas clásico — línea Swift', 'Alimento'),
  ('Mayonesa Clásico 400g', 'Georgalos', 'Mayonesa clásico — línea Georgalos', 'Alimento'),
  ('Milanesas de Soja Premium 400g', 'Granix', 'Milanesas de Soja premium — línea Granix', 'Alimento'),
  ('Dulce de Leche Premium 1kg', 'Hellmann''s', 'Dulce de Leche premium — línea Hellmann''s', 'Alimento'),
  ('Queso Cremoso Premium 250g', 'Arcor', 'Queso Cremoso premium — línea Arcor', 'Alimento')
) AS v(name, brand, description, category)
WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = v.name);

INSERT INTO products (name, brand, description, category, created_at, updated_at)
SELECT v.name, v.brand, v.description, v.category, NOW(), NOW()
FROM (VALUES
  ('Turrón Orgánico 400g', 'Knorr', 'Turrón orgánico — línea Knorr', 'Alimento'),
  ('Garbanzos Premium 200g', 'Matarazzo', 'Garbanzos premium — línea Matarazzo', 'Alimento'),
  ('Puré de Tomate Clásico 500g', 'Cabaña', 'Puré de Tomate clásico — línea Cabaña', 'Alimento'),
  ('Caramelos Orgánico 250g', 'Knorr', 'Caramelos orgánico — línea Knorr', 'Alimento'),
  ('Caramelos Tradicional 400g', 'Paladini', 'Caramelos tradicional — línea Paladini', 'Alimento'),
  ('Cereales Premium 200g', 'Molto', 'Cereales premium — línea Molto', 'Alimento'),
  ('Mermelada Orgánico 250g', 'Paladini', 'Mermelada orgánico — línea Paladini', 'Alimento'),
  ('Fideos Moñito Orgánico 200g', 'Granix', 'Fideos Moñito orgánico — línea Granix', 'Alimento'),
  ('Queso Cremoso Orgánico 250g', 'Knorr', 'Queso Cremoso orgánico — línea Knorr', 'Alimento'),
  ('Salchichas Premium 250g', 'Paladini', 'Salchichas premium — línea Paladini', 'Alimento'),
  ('Choclo en Lata Premium 200g', 'Hellmann''s', 'Choclo en Lata premium — línea Hellmann''s', 'Alimento'),
  ('Copos de Maíz Clásico 300g', 'Cabaña', 'Copos de Maíz clásico — línea Cabaña', 'Alimento'),
  ('Manteca Clásico 500g', 'Arcor', 'Manteca clásico — línea Arcor', 'Alimento'),
  ('Garbanzos Clásico 500g', 'Swift', 'Garbanzos clásico — línea Swift', 'Alimento'),
  ('Aceitunas Orgánico 200g', 'Marolio', 'Aceitunas orgánico — línea Marolio', 'Alimento'),
  ('Caldo en Cubos Premium 400g', 'Cabaña', 'Caldo en Cubos premium — línea Cabaña', 'Alimento'),
  ('Chocolate en Polvo Clásico 500g', 'Cañuelas', 'Chocolate en Polvo clásico — línea Cañuelas', 'Alimento'),
  ('Papas Fritas Premium 500g', 'Paladini', 'Papas Fritas premium — línea Paladini', 'Alimento'),
  ('Yogur Bebible Orgánico 250g', 'Cocinero', 'Yogur Bebible orgánico — línea Cocinero', 'Alimento'),
  ('Duraznos en Almíbar Premium 400g', 'Bagley', 'Duraznos en Almíbar premium — línea Bagley', 'Alimento'),
  ('Fideos Tirabuzón Light 500g', 'La Unión', 'Fideos Tirabuzón light — línea La Unión', 'Alimento'),
  ('Pan Rallado Orgánico 200g', 'Celusal', 'Pan Rallado orgánico — línea Celusal', 'Alimento'),
  ('Garbanzos Clásico 250g', 'Knorr', 'Garbanzos clásico — línea Knorr', 'Alimento'),
  ('Miel Premium 200g', 'Nucrem', 'Miel premium — línea Nucrem', 'Alimento'),
  ('Queso Cremoso Premium 300g', 'Cañuelas', 'Queso Cremoso premium — línea Cañuelas', 'Alimento'),
  ('Soda Premium 1.5L', 'Real', 'Soda premium — línea Real', 'Bebidas'),
  ('Sidra Light 1L', 'Rutini', 'Sidra light — línea Rutini', 'Bebidas'),
  ('Cerveza IPA Zero 1.5L', 'Branca', 'Cerveza IPA zero — línea Branca', 'Bebidas'),
  ('Soda Light 500ml', 'Branca', 'Soda light — línea Branca', 'Bebidas'),
  ('Vodka Reserva 1.5L', 'Stella Artois', 'Vodka reserva — línea Stella Artois', 'Bebidas'),
  ('Gaseosa Lima Limón Premium 1.5L', 'Quilmes', 'Gaseosa Lima Limón premium — línea Quilmes', 'Bebidas'),
  ('Agua Tónica Zero 750ml', 'Fanta', 'Agua Tónica zero — línea Fanta', 'Bebidas'),
  ('Vino Rosado Zero 1L', 'Real', 'Vino Rosado zero — línea Real', 'Bebidas'),
  ('Gaseosa Cola Zero 2L', 'Speed', 'Gaseosa Cola zero — línea Speed', 'Bebidas'),
  ('Vino Tinto Clásico 500ml', 'Branca', 'Vino Tinto clásico — línea Branca', 'Bebidas'),
  ('Vino Tinto Light 2L', 'Taragüi', 'Vino Tinto light — línea Taragüi', 'Bebidas'),
  ('Jugo Multifruta Clásico 500ml', 'Absolut', 'Jugo Multifruta clásico — línea Absolut', 'Bebidas'),
  ('Café Molido Premium 500ml', 'Cepita', 'Café Molido premium — línea Cepita', 'Bebidas'),
  ('Bebida Energética Clásico 2L', 'Powerade', 'Bebida Energética clásico — línea Powerade', 'Bebidas'),
  ('Gin Clásico 1.5L', 'Jameson', 'Gin clásico — línea Jameson', 'Bebidas'),
  ('Bebida Energética Reserva 750ml', 'Nescafé', 'Bebida Energética reserva — línea Nescafé', 'Bebidas'),
  ('Cerveza Lager Reserva 750ml', 'Branca', 'Cerveza Lager reserva — línea Branca', 'Bebidas'),
  ('Jugo Multifruta Reserva 2L', 'Cabrales', 'Jugo Multifruta reserva — línea Cabrales', 'Bebidas'),
  ('Cerveza Lager Premium 1.5L', 'Gordon''s', 'Cerveza Lager premium — línea Gordon''s', 'Bebidas'),
  ('Leche Chocolatada Clásico 500ml', 'Nescafé', 'Leche Chocolatada clásico — línea Nescafé', 'Bebidas'),
  ('Jugo Multifruta Reserva 1L', 'La Virginia', 'Jugo Multifruta reserva — línea La Virginia', 'Bebidas'),
  ('Sidra Premium 1.5L', 'Trapiche', 'Sidra premium — línea Trapiche', 'Bebidas'),
  ('Cerveza Lager Clásico 1L', 'Real', 'Cerveza Lager clásico — línea Real', 'Bebidas'),
  ('Vino Tinto Light 750ml', 'Cepita', 'Vino Tinto light — línea Cepita', 'Bebidas'),
  ('Soda Reserva 1L', 'Taragüi', 'Soda reserva — línea Taragüi', 'Bebidas'),
  ('Agua Mineral Clásico 1.5L', 'Nescafé', 'Agua Mineral clásico — línea Nescafé', 'Bebidas'),
  ('Cerveza Stout Premium 500ml', 'Coca-Cola', 'Cerveza Stout premium — línea Coca-Cola', 'Bebidas'),
  ('Gaseosa Cola Clásico 750ml', 'Nescafé', 'Gaseosa Cola clásico — línea Nescafé', 'Bebidas'),
  ('Café Instantáneo Zero 500ml', 'Cabrales', 'Café Instantáneo zero — línea Cabrales', 'Bebidas'),
  ('Jugo de Manzana Reserva 1.5L', 'Real', 'Jugo de Manzana reserva — línea Real', 'Bebidas'),
  ('Fernet Zero 2L', 'Stella Artois', 'Fernet zero — línea Stella Artois', 'Bebidas'),
  ('Whisky Reserva 750ml', 'Rutini', 'Whisky reserva — línea Rutini', 'Bebidas'),
  ('Licor de Café Clásico 750ml', 'Villavicencio', 'Licor de Café clásico — línea Villavicencio', 'Bebidas'),
  ('Cerveza Lager Premium 1L', 'Cabrales', 'Cerveza Lager premium — línea Cabrales', 'Bebidas'),
  ('Aperitivo Zero 1.5L', 'Chandon', 'Aperitivo zero — línea Chandon', 'Bebidas'),
  ('Café en Grano Premium 2L', 'Pepsi', 'Café en Grano premium — línea Pepsi', 'Bebidas'),
  ('Gaseosa Lima Limón Reserva 1L', 'Coca-Cola', 'Gaseosa Lima Limón reserva — línea Coca-Cola', 'Bebidas'),
  ('Fernet Clásico 2L', 'Pepsi', 'Fernet clásico — línea Pepsi', 'Bebidas'),
  ('Whisky Light 1.5L', 'Taragüi', 'Whisky light — línea Taragüi', 'Bebidas'),
  ('Whisky Premium 500ml', 'Chandon', 'Whisky premium — línea Chandon', 'Bebidas'),
  ('Vino Tinto Premium 2L', 'Fanta', 'Vino Tinto premium — línea Fanta', 'Bebidas'),
  ('Gin Light 1.5L', 'Cinzano', 'Gin light — línea Cinzano', 'Bebidas'),
  ('Vino Tinto Zero 2L', 'Chandon', 'Vino Tinto zero — línea Chandon', 'Bebidas'),
  ('Bebida Energética Premium 1L', 'Rutini', 'Bebida Energética premium — línea Rutini', 'Bebidas'),
  ('Fernet Zero 1L', 'Rutini', 'Fernet zero — línea Rutini', 'Bebidas'),
  ('Cerveza IPA Reserva 1L', 'Powerade', 'Cerveza IPA reserva — línea Powerade', 'Bebidas'),
  ('Café en Grano Reserva 2L', 'Jameson', 'Café en Grano reserva — línea Jameson', 'Bebidas'),
  ('Gaseosa Naranja Reserva 2L', 'Gatorade', 'Gaseosa Naranja reserva — línea Gatorade', 'Bebidas'),
  ('Jugo Multifruta Zero 1.5L', 'Sprite', 'Jugo Multifruta zero — línea Sprite', 'Bebidas'),
  ('Café en Grano Light 2L', 'La Virginia', 'Café en Grano light — línea La Virginia', 'Bebidas'),
  ('Infusión Té Reserva 1.5L', 'Fanta', 'Infusión Té reserva — línea Fanta', 'Bebidas'),
  ('Café Instantáneo Clásico 1L', 'Quilmes', 'Café Instantáneo clásico — línea Quilmes', 'Bebidas'),
  ('Leche Chocolatada Clásico 1.5L', 'Smirnoff', 'Leche Chocolatada clásico — línea Smirnoff', 'Bebidas'),
  ('Fernet Light 1.5L', 'Stella Artois', 'Fernet light — línea Stella Artois', 'Bebidas'),
  ('Agua Mineral Reserva 1.5L', 'Cinzano', 'Agua Mineral reserva — línea Cinzano', 'Bebidas'),
  ('Soda Clásico 750ml', 'La Virginia', 'Soda clásico — línea La Virginia', 'Bebidas'),
  ('Whisky Clásico 750ml', 'Quilmes', 'Whisky clásico — línea Quilmes', 'Bebidas'),
  ('Isotónica Reserva 750ml', 'Norton', 'Isotónica reserva — línea Norton', 'Bebidas'),
  ('Gaseosa Lima Limón Clásico 1L', 'Cepita', 'Gaseosa Lima Limón clásico — línea Cepita', 'Bebidas'),
  ('Fernet Clásico 500ml', 'Cinzano', 'Fernet clásico — línea Cinzano', 'Bebidas'),
  ('Soda Clásico 500ml', 'Coca-Cola', 'Soda clásico — línea Coca-Cola', 'Bebidas'),
  ('Agua Mineral Clásico 1L', 'Chandon', 'Agua Mineral clásico — línea Chandon', 'Bebidas'),
  ('Espumante Reserva 750ml', 'Villavicencio', 'Espumante reserva — línea Villavicencio', 'Bebidas'),
  ('Cerveza IPA Clásico 750ml', 'Pepsi', 'Cerveza IPA clásico — línea Pepsi', 'Bebidas'),
  ('Café en Grano Clásico 750ml', 'Coca-Cola', 'Café en Grano clásico — línea Coca-Cola', 'Bebidas'),
  ('Jugo Multifruta Premium 2L', 'Powerade', 'Jugo Multifruta premium — línea Powerade', 'Bebidas'),
  ('Gaseosa Cola Clásico 500ml', 'Coca-Cola', 'Gaseosa Cola clásico — línea Coca-Cola', 'Bebidas'),
  ('Gaseosa Naranja Light 750ml', 'Coca-Cola', 'Gaseosa Naranja light — línea Coca-Cola', 'Bebidas'),
  ('Cerveza IPA Light 500ml', 'Quilmes', 'Cerveza IPA light — línea Quilmes', 'Bebidas'),
  ('Aperitivo Premium 2L', 'Smirnoff', 'Aperitivo premium — línea Smirnoff', 'Bebidas'),
  ('Agua Mineral Premium 1L', 'Coca-Cola', 'Agua Mineral premium — línea Coca-Cola', 'Bebidas'),
  ('Jugo Multifruta Clásico 1.5L', 'Stella Artois', 'Jugo Multifruta clásico — línea Stella Artois', 'Bebidas'),
  ('Gin Zero 500ml', 'Cinzano', 'Gin zero — línea Cinzano', 'Bebidas'),
  ('Jugo de Manzana Zero 2L', 'Cabrales', 'Jugo de Manzana zero — línea Cabrales', 'Bebidas'),
  ('Agua Tónica Reserva 1L', 'Powerade', 'Agua Tónica reserva — línea Powerade', 'Bebidas')
) AS v(name, brand, description, category)
WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = v.name);

INSERT INTO products (name, brand, description, category, created_at, updated_at)
SELECT v.name, v.brand, v.description, v.category, NOW(), NOW()
FROM (VALUES
  ('Vino Blanco Clásico 750ml', 'Quilmes', 'Vino Blanco clásico — línea Quilmes', 'Bebidas'),
  ('Agua Mineral Zero 1L', 'Fanta', 'Agua Mineral zero — línea Fanta', 'Bebidas'),
  ('Gaseosa Lima Limón Clásico 2L', 'Nescafé', 'Gaseosa Lima Limón clásico — línea Nescafé', 'Bebidas'),
  ('Cerveza IPA Light 750ml', 'Stella Artois', 'Cerveza IPA light — línea Stella Artois', 'Bebidas'),
  ('Agua Saborizada Light 750ml', 'La Virginia', 'Agua Saborizada light — línea La Virginia', 'Bebidas'),
  ('Leche Chocolatada Clásico 1L', 'Cinzano', 'Leche Chocolatada clásico — línea Cinzano', 'Bebidas'),
  ('Soda Premium 500ml', 'Gatorade', 'Soda premium — línea Gatorade', 'Bebidas'),
  ('Cerveza IPA Premium 2L', 'La Virginia', 'Cerveza IPA premium — línea La Virginia', 'Bebidas'),
  ('Leche Chocolatada Reserva 750ml', 'Norton', 'Leche Chocolatada reserva — línea Norton', 'Bebidas'),
  ('Fernet Reserva 1.5L', 'Powerade', 'Fernet reserva — línea Powerade', 'Bebidas'),
  ('Gin Light 750ml', 'Nescafé', 'Gin light — línea Nescafé', 'Bebidas'),
  ('Agua Mineral Clásico 500ml', 'Chandon', 'Agua Mineral clásico — línea Chandon', 'Bebidas'),
  ('Gaseosa Naranja Zero 1.5L', 'Stella Artois', 'Gaseosa Naranja zero — línea Stella Artois', 'Bebidas'),
  ('Espumante Clásico 2L', 'Smirnoff', 'Espumante clásico — línea Smirnoff', 'Bebidas'),
  ('Café Molido Light 1L', 'Quilmes', 'Café Molido light — línea Quilmes', 'Bebidas'),
  ('Cerveza Stout Reserva 750ml', 'Stella Artois', 'Cerveza Stout reserva — línea Stella Artois', 'Bebidas'),
  ('Bebida Energética Reserva 1L', 'Fanta', 'Bebida Energética reserva — línea Fanta', 'Bebidas'),
  ('Whisky Light 2L', 'Coca-Cola', 'Whisky light — línea Coca-Cola', 'Bebidas'),
  ('Aperitivo Clásico 750ml', 'Chandon', 'Aperitivo clásico — línea Chandon', 'Bebidas'),
  ('Agua Mineral Light 1L', 'Fanta', 'Agua Mineral light — línea Fanta', 'Bebidas'),
  ('Café Molido Premium 2L', 'Brahma', 'Café Molido premium — línea Brahma', 'Bebidas'),
  ('Agua Saborizada Clásico 2L', 'Gatorade', 'Agua Saborizada clásico — línea Gatorade', 'Bebidas'),
  ('Café Molido Premium 1.5L', 'Real', 'Café Molido premium — línea Real', 'Bebidas'),
  ('Agua Tónica Zero 2L', 'Pepsi', 'Agua Tónica zero — línea Pepsi', 'Bebidas'),
  ('Cerveza Stout Reserva 1.5L', 'Gordon''s', 'Cerveza Stout reserva — línea Gordon''s', 'Bebidas'),
  ('Cerveza Stout Clásico 500ml', 'Brahma', 'Cerveza Stout clásico — línea Brahma', 'Bebidas'),
  ('Aperitivo Clásico 1.5L', 'Speed', 'Aperitivo clásico — línea Speed', 'Bebidas'),
  ('Isotónica Premium 500ml', 'Jameson', 'Isotónica premium — línea Jameson', 'Bebidas'),
  ('Whisky Zero 1.5L', 'Absolut', 'Whisky zero — línea Absolut', 'Bebidas'),
  ('Gaseosa Lima Limón Clásico 500ml', 'Cinzano', 'Gaseosa Lima Limón clásico — línea Cinzano', 'Bebidas'),
  ('Cerveza Lager Reserva 1L', 'Cepita', 'Cerveza Lager reserva — línea Cepita', 'Bebidas'),
  ('Cerveza Lager Light 750ml', 'Jameson', 'Cerveza Lager light — línea Jameson', 'Bebidas'),
  ('Licor de Café Light 750ml', 'Stella Artois', 'Licor de Café light — línea Stella Artois', 'Bebidas'),
  ('Agua Mineral Reserva 1L', 'Villavicencio', 'Agua Mineral reserva — línea Villavicencio', 'Bebidas'),
  ('Leche Chocolatada Clásico 750ml', 'Cepita', 'Leche Chocolatada clásico — línea Cepita', 'Bebidas'),
  ('Jugo de Naranja Light 1L', 'Sprite', 'Jugo de Naranja light — línea Sprite', 'Bebidas'),
  ('Vino Blanco Zero 500ml', 'Smirnoff', 'Vino Blanco zero — línea Smirnoff', 'Bebidas'),
  ('Agua Saborizada Zero 2L', 'Quilmes', 'Agua Saborizada zero — línea Quilmes', 'Bebidas'),
  ('Sidra Reserva 2L', 'Branca', 'Sidra reserva — línea Branca', 'Bebidas'),
  ('Jugo de Manzana Premium 750ml', 'Quilmes', 'Jugo de Manzana premium — línea Quilmes', 'Bebidas'),
  ('Aperitivo Light 2L', 'Smirnoff', 'Aperitivo light — línea Smirnoff', 'Bebidas'),
  ('Aperitivo Clásico 1L', 'Real', 'Aperitivo clásico — línea Real', 'Bebidas'),
  ('Gaseosa Cola Light 750ml', 'Norton', 'Gaseosa Cola light — línea Norton', 'Bebidas'),
  ('Gaseosa Lima Limón Premium 500ml', 'Norton', 'Gaseosa Lima Limón premium — línea Norton', 'Bebidas'),
  ('Agua Saborizada Zero 1L', 'Taragüi', 'Agua Saborizada zero — línea Taragüi', 'Bebidas'),
  ('Gin Light 500ml', 'Absolut', 'Gin light — línea Absolut', 'Bebidas'),
  ('Gaseosa Cola Zero 750ml', 'Taragüi', 'Gaseosa Cola zero — línea Taragüi', 'Bebidas'),
  ('Gaseosa Naranja Reserva 1.5L', 'Trapiche', 'Gaseosa Naranja reserva — línea Trapiche', 'Bebidas'),
  ('Vino Tinto Premium 750ml', 'Norton', 'Vino Tinto premium — línea Norton', 'Bebidas'),
  ('Soda Premium 750ml', 'Coca-Cola', 'Soda premium — línea Coca-Cola', 'Bebidas'),
  ('Camisa Niña M', 'Umbro', 'Camisa niña — línea Umbro', 'Indumentaria'),
  ('Botas Unisex L', 'Wrangler', 'Botas unisex — línea Wrangler', 'Indumentaria'),
  ('Vestido Niña XXL', 'Adidas', 'Vestido niña — línea Adidas', 'Indumentaria'),
  ('Calza Niña L', 'Lacoste', 'Calza niña — línea Lacoste', 'Indumentaria'),
  ('Pantalón Unisex S', 'Adidas', 'Pantalón unisex — línea Adidas', 'Indumentaria'),
  ('Short Mujer XXL', 'Wrangler', 'Short mujer — línea Wrangler', 'Indumentaria'),
  ('Medias Niña S', 'Rusty', 'Medias niña — línea Rusty', 'Indumentaria'),
  ('Gorra Mujer XXL', 'Rip Curl', 'Gorra mujer — línea Rip Curl', 'Indumentaria'),
  ('Zapatillas Unisex L', 'Legacy', 'Zapatillas unisex — línea Legacy', 'Indumentaria'),
  ('Short Mujer M', 'Prune', 'Short mujer — línea Prune', 'Indumentaria'),
  ('Sandalias Hombre XL', 'Kevingston', 'Sandalias hombre — línea Kevingston', 'Indumentaria'),
  ('Jean Niño L', 'Columbia', 'Jean niño — línea Columbia', 'Indumentaria'),
  ('Short Niño M', 'Ombu', 'Short niño — línea Ombu', 'Indumentaria'),
  ('Vestido Niña XL', 'Nike', 'Vestido niña — línea Nike', 'Indumentaria'),
  ('Medias Hombre L', 'Nike', 'Medias hombre — línea Nike', 'Indumentaria'),
  ('Sombrero Hombre M', 'Nike', 'Sombrero hombre — línea Nike', 'Indumentaria'),
  ('Camisón Niño L', 'Portsaid', 'Camisón niño — línea Portsaid', 'Indumentaria'),
  ('Calza Niño L', 'Asics', 'Calza niño — línea Asics', 'Indumentaria'),
  ('Remera Niña XXL', 'Puma', 'Remera niña — línea Puma', 'Indumentaria'),
  ('Vestido Niño S', 'Nike', 'Vestido niño — línea Nike', 'Indumentaria'),
  ('Camisa Niño XXL', 'Zara', 'Camisa niño — línea Zara', 'Indumentaria'),
  ('Pollera Hombre S', 'Puma', 'Pollera hombre — línea Puma', 'Indumentaria'),
  ('Sombrero Hombre XL', 'Columbia', 'Sombrero hombre — línea Columbia', 'Indumentaria'),
  ('Cinturón Mujer S', 'Columbia', 'Cinturón mujer — línea Columbia', 'Indumentaria'),
  ('Calza Hombre XXL', 'Kevingston', 'Calza hombre — línea Kevingston', 'Indumentaria'),
  ('Bufanda Unisex L', 'Legacy', 'Bufanda unisex — línea Legacy', 'Indumentaria'),
  ('Buzo Niña S', 'Nike', 'Buzo niña — línea Nike', 'Indumentaria'),
  ('Vestido Hombre XXL', 'Adidas', 'Vestido hombre — línea Adidas', 'Indumentaria'),
  ('Remera Unisex XXL', 'Zara', 'Remera unisex — línea Zara', 'Indumentaria'),
  ('Gorra Mujer S', 'Zara', 'Gorra mujer — línea Zara', 'Indumentaria'),
  ('Ropa Interior Niño L', 'Lacoste', 'Ropa Interior niño — línea Lacoste', 'Indumentaria'),
  ('Short Unisex S', 'Umbro', 'Short unisex — línea Umbro', 'Indumentaria'),
  ('Musculosa Niño XL', 'Zara', 'Musculosa niño — línea Zara', 'Indumentaria'),
  ('Ropa Interior Mujer XXL', 'Kevingston', 'Ropa Interior mujer — línea Kevingston', 'Indumentaria'),
  ('Sandalias Niña XL', 'Levis', 'Sandalias niña — línea Levis', 'Indumentaria'),
  ('Vestido Hombre S', 'Wrangler', 'Vestido hombre — línea Wrangler', 'Indumentaria'),
  ('Camisón Niña XL', 'Columbia', 'Camisón niña — línea Columbia', 'Indumentaria'),
  ('Zapatillas Mujer L', 'Zara', 'Zapatillas mujer — línea Zara', 'Indumentaria'),
  ('Medias Hombre XXL', 'Lacoste', 'Medias hombre — línea Lacoste', 'Indumentaria'),
  ('Campera Mujer M', 'Rip Curl', 'Campera mujer — línea Rip Curl', 'Indumentaria'),
  ('Musculosa Hombre L', 'Portsaid', 'Musculosa hombre — línea Portsaid', 'Indumentaria'),
  ('Sweater Mujer L', 'Vitamina', 'Sweater mujer — línea Vitamina', 'Indumentaria'),
  ('Musculosa Hombre S', 'Prune', 'Musculosa hombre — línea Prune', 'Indumentaria'),
  ('Zapatillas Niño M', 'Adidas', 'Zapatillas niño — línea Adidas', 'Indumentaria'),
  ('Remera Hombre XXL', 'Adidas', 'Remera hombre — línea Adidas', 'Indumentaria'),
  ('Gorra Niño XXL', 'Puma', 'Gorra niño — línea Puma', 'Indumentaria'),
  ('Buzo Mujer L', 'Levis', 'Buzo mujer — línea Levis', 'Indumentaria'),
  ('Sombrero Mujer XXL', 'Kevingston', 'Sombrero mujer — línea Kevingston', 'Indumentaria'),
  ('Musculosa Niña S', 'Ayres', 'Musculosa niña — línea Ayres', 'Indumentaria'),
  ('Cinturón Unisex M', 'Legacy', 'Cinturón unisex — línea Legacy', 'Indumentaria')
) AS v(name, brand, description, category)
WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = v.name);

INSERT INTO products (name, brand, description, category, created_at, updated_at)
SELECT v.name, v.brand, v.description, v.category, NOW(), NOW()
FROM (VALUES
  ('Piyama Unisex S', 'Adidas', 'Piyama unisex — línea Adidas', 'Indumentaria'),
  ('Ropa Interior Niña XXL', 'Vitamina', 'Ropa Interior niña — línea Vitamina', 'Indumentaria'),
  ('Zapatillas Mujer M', 'Topper', 'Zapatillas mujer — línea Topper', 'Indumentaria'),
  ('Botas Hombre XXL', 'Adidas', 'Botas hombre — línea Adidas', 'Indumentaria'),
  ('Remera Hombre S', 'Puma', 'Remera hombre — línea Puma', 'Indumentaria'),
  ('Piyama Mujer M', 'Nike', 'Piyama mujer — línea Nike', 'Indumentaria'),
  ('Remera Unisex S', 'Kevingston', 'Remera unisex — línea Kevingston', 'Indumentaria'),
  ('Guantes Hombre XL', 'Adidas', 'Guantes hombre — línea Adidas', 'Indumentaria'),
  ('Short Niño XXL', 'Legacy', 'Short niño — línea Legacy', 'Indumentaria'),
  ('Remera Unisex XL', 'Wrangler', 'Remera unisex — línea Wrangler', 'Indumentaria'),
  ('Pantalón Unisex L', 'Adidas', 'Pantalón unisex — línea Adidas', 'Indumentaria'),
  ('Pollera Unisex S', 'Columbia', 'Pollera unisex — línea Columbia', 'Indumentaria'),
  ('Mochila Hombre L', 'Zara', 'Mochila hombre — línea Zara', 'Indumentaria'),
  ('Medias Unisex L', 'Asics', 'Medias unisex — línea Asics', 'Indumentaria'),
  ('Camisa Hombre M', 'Nike', 'Camisa hombre — línea Nike', 'Indumentaria'),
  ('Zapatillas Hombre L', 'Asics', 'Zapatillas hombre — línea Asics', 'Indumentaria'),
  ('Mochila Mujer XL', 'Ombu', 'Mochila mujer — línea Ombu', 'Indumentaria'),
  ('Short Unisex XL', 'Topper', 'Short unisex — línea Topper', 'Indumentaria'),
  ('Musculosa Unisex XL', 'Nike', 'Musculosa unisex — línea Nike', 'Indumentaria'),
  ('Guantes Hombre XXL', 'Topper', 'Guantes hombre — línea Topper', 'Indumentaria'),
  ('Gorra Niño L', 'Columbia', 'Gorra niño — línea Columbia', 'Indumentaria'),
  ('Pantalón Niño XXL', 'Lacoste', 'Pantalón niño — línea Lacoste', 'Indumentaria'),
  ('Camisa Niño L', 'Legacy', 'Camisa niño — línea Legacy', 'Indumentaria'),
  ('Piyama Hombre S', 'Adidas', 'Piyama hombre — línea Adidas', 'Indumentaria'),
  ('Gorra Unisex S', 'Portsaid', 'Gorra unisex — línea Portsaid', 'Indumentaria'),
  ('Guantes Niña XL', 'Prune', 'Guantes niña — línea Prune', 'Indumentaria'),
  ('Medias Niño M', 'Ombu', 'Medias niño — línea Ombu', 'Indumentaria'),
  ('Musculosa Mujer M', 'Portsaid', 'Musculosa mujer — línea Portsaid', 'Indumentaria'),
  ('Jean Hombre XXL', 'Asics', 'Jean hombre — línea Asics', 'Indumentaria'),
  ('Medias Niña XL', 'Columbia', 'Medias niña — línea Columbia', 'Indumentaria'),
  ('Gorra Unisex XL', 'Columbia', 'Gorra unisex — línea Columbia', 'Indumentaria'),
  ('Pantalón Niña XXL', 'Ayres', 'Pantalón niña — línea Ayres', 'Indumentaria'),
  ('Mochila Unisex L', 'Lacoste', 'Mochila unisex — línea Lacoste', 'Indumentaria'),
  ('Sandalias Unisex S', 'Prune', 'Sandalias unisex — línea Prune', 'Indumentaria'),
  ('Sombrero Mujer L', 'Nike', 'Sombrero mujer — línea Nike', 'Indumentaria'),
  ('Camisa Niña S', 'Levis', 'Camisa niña — línea Levis', 'Indumentaria'),
  ('Bermuda Niña L', 'Legacy', 'Bermuda niña — línea Legacy', 'Indumentaria'),
  ('Short Unisex M', 'Wrangler', 'Short unisex — línea Wrangler', 'Indumentaria'),
  ('Pollera Mujer L', 'Rip Curl', 'Pollera mujer — línea Rip Curl', 'Indumentaria'),
  ('Medias Unisex M', 'Adidas', 'Medias unisex — línea Adidas', 'Indumentaria'),
  ('Calza Mujer XXL', 'Columbia', 'Calza mujer — línea Columbia', 'Indumentaria'),
  ('Musculosa Niña M', 'Levis', 'Musculosa niña — línea Levis', 'Indumentaria'),
  ('Pollera Niño XXL', 'Ayres', 'Pollera niño — línea Ayres', 'Indumentaria'),
  ('Jean Unisex M', 'Kevingston', 'Jean unisex — línea Kevingston', 'Indumentaria'),
  ('Piyama Niña L', 'Rusty', 'Piyama niña — línea Rusty', 'Indumentaria'),
  ('Piyama Niña M', 'Umbro', 'Piyama niña — línea Umbro', 'Indumentaria'),
  ('Sombrero Unisex XXL', 'Vitamina', 'Sombrero unisex — línea Vitamina', 'Indumentaria'),
  ('Pantalón Niño M', 'Ombu', 'Pantalón niño — línea Ombu', 'Indumentaria'),
  ('Ropa Interior Niño M', 'Portsaid', 'Ropa Interior niño — línea Portsaid', 'Indumentaria'),
  ('Zapatillas Unisex S', 'Zara', 'Zapatillas unisex — línea Zara', 'Indumentaria'),
  ('Calza Hombre L', 'Ombu', 'Calza hombre — línea Ombu', 'Indumentaria'),
  ('Pantalón Niña M', 'Prune', 'Pantalón niña — línea Prune', 'Indumentaria'),
  ('Sweater Niña M', 'Puma', 'Sweater niña — línea Puma', 'Indumentaria'),
  ('Calza Niño XL', 'Vitamina', 'Calza niño — línea Vitamina', 'Indumentaria'),
  ('Short Mujer XL', 'Wrangler', 'Short mujer — línea Wrangler', 'Indumentaria'),
  ('Zapatillas Hombre XL', 'Legacy', 'Zapatillas hombre — línea Legacy', 'Indumentaria'),
  ('Gorra Mujer L', 'Vitamina', 'Gorra mujer — línea Vitamina', 'Indumentaria'),
  ('Bermuda Unisex XXL', 'Lacoste', 'Bermuda unisex — línea Lacoste', 'Indumentaria'),
  ('Botas Niño S', 'Lacoste', 'Botas niño — línea Lacoste', 'Indumentaria'),
  ('Botas Unisex XXL', 'Kevingston', 'Botas unisex — línea Kevingston', 'Indumentaria'),
  ('Pantalón Unisex M', 'Umbro', 'Pantalón unisex — línea Umbro', 'Indumentaria'),
  ('Camisón Unisex M', 'Ayres', 'Camisón unisex — línea Ayres', 'Indumentaria'),
  ('Jean Niño XL', 'Legacy', 'Jean niño — línea Legacy', 'Indumentaria'),
  ('Jean Hombre S', 'Levis', 'Jean hombre — línea Levis', 'Indumentaria'),
  ('Piyama Mujer S', 'Nike', 'Piyama mujer — línea Nike', 'Indumentaria'),
  ('Ropa Interior Niño XXL', 'Adidas', 'Ropa Interior niño — línea Adidas', 'Indumentaria'),
  ('Sandalias Mujer S', 'Wrangler', 'Sandalias mujer — línea Wrangler', 'Indumentaria'),
  ('Cinturón Mujer L', 'Ayres', 'Cinturón mujer — línea Ayres', 'Indumentaria'),
  ('Pantalón Hombre XL', 'Ombu', 'Pantalón hombre — línea Ombu', 'Indumentaria'),
  ('Sandalias Hombre XXL', 'Adidas', 'Sandalias hombre — línea Adidas', 'Indumentaria'),
  ('Remera Niña S', 'Ayres', 'Remera niña — línea Ayres', 'Indumentaria'),
  ('Zapatillas Mujer XL', 'Kevingston', 'Zapatillas mujer — línea Kevingston', 'Indumentaria'),
  ('Mochila Niña XXL', 'Portsaid', 'Mochila niña — línea Portsaid', 'Indumentaria'),
  ('Pollera Hombre M', 'Nike', 'Pollera hombre — línea Nike', 'Indumentaria'),
  ('Bermuda Niño M', 'Topper', 'Bermuda niño — línea Topper', 'Indumentaria'),
  ('Smartwatch Pro 256GB', 'Electrolux', 'Smartwatch pro — línea Electrolux', 'Electrónica'),
  ('Ventilador Básico 256GB', 'HP', 'Ventilador básico — línea HP', 'Electrónica'),
  ('Cargador Pro 55"', 'Motorola', 'Cargador pro — línea Motorola', 'Electrónica'),
  ('Cargador Básico 256GB', 'Whirlpool', 'Cargador básico — línea Whirlpool', 'Electrónica'),
  ('Heladera Pro 55"', 'Noblex', 'Heladera pro — línea Noblex', 'Electrónica'),
  ('Aire Acondicionado Pro 128GB', 'Dell', 'Aire Acondicionado pro — línea Dell', 'Electrónica'),
  ('Heladera Ultra 43"', 'Hitachi', 'Heladera ultra — línea Hitachi', 'Electrónica'),
  ('Ventilador Plus 43"', 'Motorola', 'Ventilador plus — línea Motorola', 'Electrónica'),
  ('Smart TV Ultra 32"', 'Samsung', 'Smart TV ultra — línea Samsung', 'Electrónica'),
  ('Plancha Pro 55"', 'Xiaomi', 'Plancha pro — línea Xiaomi', 'Electrónica'),
  ('Plancha Pro 64GB', 'LG', 'Plancha pro — línea LG', 'Electrónica'),
  ('Smart TV Básico 128GB', 'Panasonic', 'Smart TV básico — línea Panasonic', 'Electrónica'),
  ('Auriculares Plus 128GB', 'Atma', 'Auriculares plus — línea Atma', 'Electrónica'),
  ('Router WiFi Estándar 43"', 'LG', 'Router WiFi estándar — línea LG', 'Electrónica'),
  ('Ventilador Básico 43"', 'Samsung', 'Ventilador básico — línea Samsung', 'Electrónica'),
  ('Teclado Plus 64GB', 'Philips', 'Teclado plus — línea Philips', 'Electrónica'),
  ('Celular Pro 64GB', 'Dell', 'Celular pro — línea Dell', 'Electrónica'),
  ('Power Bank Básico 32"', 'Panasonic', 'Power Bank básico — línea Panasonic', 'Electrónica'),
  ('Cámara Digital Básico 55"', 'Motorola', 'Cámara Digital básico — línea Motorola', 'Electrónica'),
  ('Parlante Bluetooth Pro 55"', 'Samsung', 'Parlante Bluetooth pro — línea Samsung', 'Electrónica'),
  ('Cargador Ultra 64GB', 'Philips', 'Cargador ultra — línea Philips', 'Electrónica'),
  ('Notebook Básico 55"', 'Panasonic', 'Notebook básico — línea Panasonic', 'Electrónica'),
  ('Lavarropas Básico 256GB', 'Motorola', 'Lavarropas básico — línea Motorola', 'Electrónica'),
  ('Power Bank Pro 32"', 'Philips', 'Power Bank pro — línea Philips', 'Electrónica'),
  ('Ventilador Pro 43"', 'Atma', 'Ventilador pro — línea Atma', 'Electrónica')
) AS v(name, brand, description, category)
WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = v.name);

INSERT INTO products (name, brand, description, category, created_at, updated_at)
SELECT v.name, v.brand, v.description, v.category, NOW(), NOW()
FROM (VALUES
  ('Mouse Pro 64GB', 'Philips', 'Mouse pro — línea Philips', 'Electrónica'),
  ('Heladera Pro 64GB', 'Whirlpool', 'Heladera pro — línea Whirlpool', 'Electrónica'),
  ('Consola de Videojuegos Estándar 55"', 'Noblex', 'Consola de Videojuegos estándar — línea Noblex', 'Electrónica'),
  ('Cargador Ultra 32"', 'Electrolux', 'Cargador ultra — línea Electrolux', 'Electrónica'),
  ('Parlante Bluetooth Básico 128GB', 'Lenovo', 'Parlante Bluetooth básico — línea Lenovo', 'Electrónica'),
  ('Microondas Ultra 64GB', 'JBL', 'Microondas ultra — línea JBL', 'Electrónica'),
  ('Monitor Básico 64GB', 'Drean', 'Monitor básico — línea Drean', 'Electrónica'),
  ('Monitor Ultra 256GB', 'Noblex', 'Monitor ultra — línea Noblex', 'Electrónica'),
  ('Ventilador Pro 128GB', 'Whirlpool', 'Ventilador pro — línea Whirlpool', 'Electrónica'),
  ('Consola de Videojuegos Estándar 43"', 'Samsung', 'Consola de Videojuegos estándar — línea Samsung', 'Electrónica'),
  ('Cafetera Eléctrica Ultra 256GB', 'Sony', 'Cafetera Eléctrica ultra — línea Sony', 'Electrónica'),
  ('Consola de Videojuegos Ultra 55"', 'Peabody', 'Consola de Videojuegos ultra — línea Peabody', 'Electrónica'),
  ('Parlante Bluetooth Ultra 55"', 'Motorola', 'Parlante Bluetooth ultra — línea Motorola', 'Electrónica'),
  ('Plancha Plus 128GB', 'Electrolux', 'Plancha plus — línea Electrolux', 'Electrónica'),
  ('Cargador Básico 64GB', 'Philips', 'Cargador básico — línea Philips', 'Electrónica'),
  ('Cafetera Eléctrica Básico 128GB', 'Hitachi', 'Cafetera Eléctrica básico — línea Hitachi', 'Electrónica'),
  ('Celular Básico 256GB', 'JBL', 'Celular básico — línea JBL', 'Electrónica'),
  ('Heladera Pro 43"', 'LG', 'Heladera pro — línea LG', 'Electrónica'),
  ('Microondas Ultra 256GB', 'Xiaomi', 'Microondas ultra — línea Xiaomi', 'Electrónica'),
  ('Smart TV Básico 64GB', 'JBL', 'Smart TV básico — línea JBL', 'Electrónica'),
  ('Aspiradora Ultra 43"', 'HP', 'Aspiradora ultra — línea HP', 'Electrónica'),
  ('Teclado Estándar 55"', 'Philips', 'Teclado estándar — línea Philips', 'Electrónica'),
  ('Power Bank Ultra 43"', 'LG', 'Power Bank ultra — línea LG', 'Electrónica'),
  ('Power Bank Estándar 256GB', 'Motorola', 'Power Bank estándar — línea Motorola', 'Electrónica'),
  ('Cafetera Eléctrica Ultra 32"', 'Xiaomi', 'Cafetera Eléctrica ultra — línea Xiaomi', 'Electrónica'),
  ('Microondas Básico 43"', 'TCL', 'Microondas básico — línea TCL', 'Electrónica'),
  ('Cámara Digital Pro 43"', 'Panasonic', 'Cámara Digital pro — línea Panasonic', 'Electrónica'),
  ('Impresora Estándar 64GB', 'Sony', 'Impresora estándar — línea Sony', 'Electrónica'),
  ('Freidora de Aire Ultra 64GB', 'HP', 'Freidora de Aire ultra — línea HP', 'Electrónica'),
  ('Freidora de Aire Básico 43"', 'Dell', 'Freidora de Aire básico — línea Dell', 'Electrónica'),
  ('Parlante Bluetooth Plus 256GB', 'TCL', 'Parlante Bluetooth plus — línea TCL', 'Electrónica'),
  ('Aire Acondicionado Básico 32"', 'Dell', 'Aire Acondicionado básico — línea Dell', 'Electrónica'),
  ('Power Bank Pro 256GB', 'Whirlpool', 'Power Bank pro — línea Whirlpool', 'Electrónica'),
  ('Smart TV Estándar 256GB', 'Xiaomi', 'Smart TV estándar — línea Xiaomi', 'Electrónica'),
  ('Notebook Estándar 128GB', 'LG', 'Notebook estándar — línea LG', 'Electrónica'),
  ('Lavarropas Básico 43"', 'Xiaomi', 'Lavarropas básico — línea Xiaomi', 'Electrónica'),
  ('Notebook Pro 32"', 'Peabody', 'Notebook pro — línea Peabody', 'Electrónica'),
  ('Parlante Bluetooth Pro 128GB', 'Peabody', 'Parlante Bluetooth pro — línea Peabody', 'Electrónica'),
  ('Auriculares Pro 32"', 'Xiaomi', 'Auriculares pro — línea Xiaomi', 'Electrónica'),
  ('Lavarropas Ultra 64GB', 'Lenovo', 'Lavarropas ultra — línea Lenovo', 'Electrónica'),
  ('Impresora Estándar 256GB', 'Motorola', 'Impresora estándar — línea Motorola', 'Electrónica'),
  ('Plancha Pro 32"', 'Whirlpool', 'Plancha pro — línea Whirlpool', 'Electrónica'),
  ('Freidora de Aire Ultra 55"', 'Logitech', 'Freidora de Aire ultra — línea Logitech', 'Electrónica'),
  ('Cafetera Eléctrica Pro 32"', 'Sony', 'Cafetera Eléctrica pro — línea Sony', 'Electrónica'),
  ('Ventilador Estándar 256GB', 'HP', 'Ventilador estándar — línea HP', 'Electrónica'),
  ('Celular Pro 43"', 'Electrolux', 'Celular pro — línea Electrolux', 'Electrónica'),
  ('Smartwatch Básico 64GB', 'Peabody', 'Smartwatch básico — línea Peabody', 'Electrónica'),
  ('Microondas Ultra 43"', 'Hitachi', 'Microondas ultra — línea Hitachi', 'Electrónica'),
  ('Consola de Videojuegos Básico 256GB', 'HP', 'Consola de Videojuegos básico — línea HP', 'Electrónica'),
  ('Aire Acondicionado Plus 32"', 'Atma', 'Aire Acondicionado plus — línea Atma', 'Electrónica'),
  ('Power Bank Estándar 43"', 'Hitachi', 'Power Bank estándar — línea Hitachi', 'Electrónica'),
  ('Auriculares Pro 55"', 'Dell', 'Auriculares pro — línea Dell', 'Electrónica'),
  ('Smartwatch Plus 64GB', 'Drean', 'Smartwatch plus — línea Drean', 'Electrónica'),
  ('Tablet Ultra 43"', 'Atma', 'Tablet ultra — línea Atma', 'Electrónica'),
  ('Teclado Estándar 64GB', 'Xiaomi', 'Teclado estándar — línea Xiaomi', 'Electrónica'),
  ('Microondas Básico 32"', 'Whirlpool', 'Microondas básico — línea Whirlpool', 'Electrónica'),
  ('Microondas Plus 32"', 'Xiaomi', 'Microondas plus — línea Xiaomi', 'Electrónica'),
  ('Microondas Estándar 55"', 'Whirlpool', 'Microondas estándar — línea Whirlpool', 'Electrónica'),
  ('Heladera Plus 128GB', 'HP', 'Heladera plus — línea HP', 'Electrónica'),
  ('Lavarropas Plus 43"', 'LG', 'Lavarropas plus — línea LG', 'Electrónica'),
  ('Consola de Videojuegos Plus 43"', 'Drean', 'Consola de Videojuegos plus — línea Drean', 'Electrónica'),
  ('Heladera Básico 256GB', 'Dell', 'Heladera básico — línea Dell', 'Electrónica'),
  ('Cargador Pro 256GB', 'Sony', 'Cargador pro — línea Sony', 'Electrónica'),
  ('Smartwatch Plus 256GB', 'Peabody', 'Smartwatch plus — línea Peabody', 'Electrónica'),
  ('Notebook Pro 64GB', 'Whirlpool', 'Notebook pro — línea Whirlpool', 'Electrónica'),
  ('Lavarropas Estándar 128GB', 'Philips', 'Lavarropas estándar — línea Philips', 'Electrónica'),
  ('Router WiFi Ultra 55"', 'Samsung', 'Router WiFi ultra — línea Samsung', 'Electrónica'),
  ('Lavarropas Ultra 32"', 'Logitech', 'Lavarropas ultra — línea Logitech', 'Electrónica'),
  ('Ventilador Ultra 55"', 'Drean', 'Ventilador ultra — línea Drean', 'Electrónica'),
  ('Auriculares Estándar 64GB', 'Sony', 'Auriculares estándar — línea Sony', 'Electrónica'),
  ('Notebook Plus 32"', 'Atma', 'Notebook plus — línea Atma', 'Electrónica'),
  ('Cafetera Eléctrica Básico 55"', 'Electrolux', 'Cafetera Eléctrica básico — línea Electrolux', 'Electrónica'),
  ('Tablet Ultra 55"', 'TCL', 'Tablet ultra — línea TCL', 'Electrónica'),
  ('Power Bank Ultra 55"', 'Lenovo', 'Power Bank ultra — línea Lenovo', 'Electrónica'),
  ('Tablet Ultra 128GB', 'Hitachi', 'Tablet ultra — línea Hitachi', 'Electrónica'),
  ('Mouse Ultra 43"', 'HP', 'Mouse ultra — línea HP', 'Electrónica'),
  ('Cámara Digital Básico 64GB', 'Atma', 'Cámara Digital básico — línea Atma', 'Electrónica'),
  ('Router WiFi Estándar 55"', 'Lenovo', 'Router WiFi estándar — línea Lenovo', 'Electrónica'),
  ('Freidora de Aire Estándar 128GB', 'Philips', 'Freidora de Aire estándar — línea Philips', 'Electrónica'),
  ('Mouse Ultra 128GB', 'Hitachi', 'Mouse ultra — línea Hitachi', 'Electrónica'),
  ('Cámara Digital Ultra 55"', 'Lenovo', 'Cámara Digital ultra — línea Lenovo', 'Electrónica'),
  ('Smartwatch Plus 128GB', 'JBL', 'Smartwatch plus — línea JBL', 'Electrónica'),
  ('Plancha Básico 55"', 'Lenovo', 'Plancha básico — línea Lenovo', 'Electrónica'),
  ('Celular Pro 256GB', 'LG', 'Celular pro — línea LG', 'Electrónica'),
  ('Power Bank Estándar 128GB', 'Whirlpool', 'Power Bank estándar — línea Whirlpool', 'Electrónica'),
  ('Cámara Digital Pro 55"', 'Logitech', 'Cámara Digital pro — línea Logitech', 'Electrónica'),
  ('Impresora Pro 32"', 'Atma', 'Impresora pro — línea Atma', 'Electrónica'),
  ('Plancha Estándar 64GB', 'Philips', 'Plancha estándar — línea Philips', 'Electrónica'),
  ('Auriculares Ultra 128GB', 'Dell', 'Auriculares ultra — línea Dell', 'Electrónica'),
  ('Cafetera Eléctrica Plus 64GB', 'Noblex', 'Cafetera Eléctrica plus — línea Noblex', 'Electrónica'),
  ('Lavarropas Plus 32"', 'Philips', 'Lavarropas plus — línea Philips', 'Electrónica'),
  ('Impresora Pro 128GB', 'LG', 'Impresora pro — línea LG', 'Electrónica'),
  ('Impresora Plus 64GB', 'Peabody', 'Impresora plus — línea Peabody', 'Electrónica'),
  ('Lavarropas Ultra 55"', 'TCL', 'Lavarropas ultra — línea TCL', 'Electrónica'),
  ('Tablet Pro 128GB', 'Peabody', 'Tablet pro — línea Peabody', 'Electrónica'),
  ('Monitor Ultra 32"', 'Motorola', 'Monitor ultra — línea Motorola', 'Electrónica'),
  ('Teclado Ultra 43"', 'Samsung', 'Teclado ultra — línea Samsung', 'Electrónica'),
  ('Cargador Plus 256GB', 'LG', 'Cargador plus — línea LG', 'Electrónica'),
  ('Impresora Ultra 55"', 'Logitech', 'Impresora ultra — línea Logitech', 'Electrónica'),
  ('Tablet Básico 43"', 'Whirlpool', 'Tablet básico — línea Whirlpool', 'Electrónica')
) AS v(name, brand, description, category)
WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = v.name);

INSERT INTO products (name, brand, description, category, created_at, updated_at)
SELECT v.name, v.brand, v.description, v.category, NOW(), NOW()
FROM (VALUES
  ('Cortina Compacto Grande', 'Alba', 'Cortina compacto — línea Alba', 'Hogar'),
  ('Escoba Clásico Individual', 'Stanley', 'Escoba clásico — línea Stanley', 'Hogar'),
  ('Vajilla x12 Deluxe Matrimonial', 'Piazza', 'Vajilla x12 deluxe — línea Piazza', 'Hogar'),
  ('Termo Compacto Grande', 'Basement', 'Termo compacto — línea Basement', 'Hogar'),
  ('Portarretratos Compacto Matrimonial', 'Vittal', 'Portarretratos compacto — línea Vittal', 'Hogar'),
  ('Set de Ollas Deluxe Chico', 'Basement', 'Set de Ollas deluxe — línea Basement', 'Hogar'),
  ('Organizador Compacto Mediano', 'Alba', 'Organizador compacto — línea Alba', 'Hogar'),
  ('Cortina Compacto Matrimonial', 'Lumilagro', 'Cortina compacto — línea Lumilagro', 'Hogar'),
  ('Toallas Moderno Mediano', 'Stanley', 'Toallas moderno — línea Stanley', 'Hogar'),
  ('Sartén Compacto Chico', 'Tramontina', 'Sartén compacto — línea Tramontina', 'Hogar'),
  ('Maceta Compacto Individual', 'Alba', 'Maceta compacto — línea Alba', 'Hogar'),
  ('Tazas x6 Moderno Grande', 'Bariloche', 'Tazas x6 moderno — línea Bariloche', 'Hogar'),
  ('Espejo Compacto Grande', 'Stanley', 'Espejo compacto — línea Stanley', 'Hogar'),
  ('Sartén Premium Individual', 'Piazza', 'Sartén premium — línea Piazza', 'Hogar'),
  ('Maceta Clásico Grande', 'Nadín', 'Maceta clásico — línea Nadín', 'Hogar'),
  ('Alfombra Compacto Chico', 'Vittal', 'Alfombra compacto — línea Vittal', 'Hogar'),
  ('Mate Compacto Individual', 'Lumilagro', 'Mate compacto — línea Lumilagro', 'Hogar'),
  ('Lámpara de Pie Deluxe Grande', 'Basement', 'Lámpara de Pie deluxe — línea Basement', 'Hogar'),
  ('Acolchado Deluxe Grande', 'Piazza', 'Acolchado deluxe — línea Piazza', 'Hogar'),
  ('Set de Ollas Premium Chico', 'Cannon', 'Set de Ollas premium — línea Cannon', 'Hogar'),
  ('Alfombra Clásico Chico', 'Piazza', 'Alfombra clásico — línea Piazza', 'Hogar'),
  ('Silla Deluxe Matrimonial', 'Essen', 'Silla deluxe — línea Essen', 'Hogar'),
  ('Cubiertos x24 Moderno Individual', 'Basement', 'Cubiertos x24 moderno — línea Basement', 'Hogar'),
  ('Cortina Premium Mediano', 'Essen', 'Cortina premium — línea Essen', 'Hogar'),
  ('Alfombra Deluxe Grande', 'Vittal', 'Alfombra deluxe — línea Vittal', 'Hogar'),
  ('Cortina Premium Chico', 'Tramontina', 'Cortina premium — línea Tramontina', 'Hogar'),
  ('Acolchado Moderno Mediano', 'Umco', 'Acolchado moderno — línea Umco', 'Hogar'),
  ('Escoba Premium Mediano', 'Stanley', 'Escoba premium — línea Stanley', 'Hogar'),
  ('Sartén Deluxe Grande', 'Piazza', 'Sartén deluxe — línea Piazza', 'Hogar'),
  ('Juego de Sábanas Compacto Grande', 'Bariloche', 'Juego de Sábanas compacto — línea Bariloche', 'Hogar'),
  ('Alfombra Premium Individual', 'Alba', 'Alfombra premium — línea Alba', 'Hogar'),
  ('Mesa Ratona Deluxe Mediano', 'Bariloche', 'Mesa Ratona deluxe — línea Bariloche', 'Hogar'),
  ('Termo Deluxe Mediano', 'Nadín', 'Termo deluxe — línea Nadín', 'Hogar'),
  ('Mate Moderno Mediano', 'Tramontina', 'Mate moderno — línea Tramontina', 'Hogar'),
  ('Espejo Deluxe Mediano', 'Essen', 'Espejo deluxe — línea Essen', 'Hogar'),
  ('Juego de Sábanas Moderno Mediano', 'Stanley', 'Juego de Sábanas moderno — línea Stanley', 'Hogar'),
  ('Sillón Premium Chico', 'Tramontina', 'Sillón premium — línea Tramontina', 'Hogar'),
  ('Alfombra Clásico Grande', 'Piazza', 'Alfombra clásico — línea Piazza', 'Hogar'),
  ('Escoba Moderno Individual', 'Alba', 'Escoba moderno — línea Alba', 'Hogar'),
  ('Sillón Premium Grande', 'Umco', 'Sillón premium — línea Umco', 'Hogar'),
  ('Juego de Sábanas Deluxe Matrimonial', 'Piazza', 'Juego de Sábanas deluxe — línea Piazza', 'Hogar'),
  ('Perchero Moderno Chico', 'Piazza', 'Perchero moderno — línea Piazza', 'Hogar'),
  ('Cubiertos x24 Premium Matrimonial', 'Nadín', 'Cubiertos x24 premium — línea Nadín', 'Hogar'),
  ('Juego de Sábanas Moderno Grande', 'Lumilagro', 'Juego de Sábanas moderno — línea Lumilagro', 'Hogar'),
  ('Silla Deluxe Individual', 'Nadín', 'Silla deluxe — línea Nadín', 'Hogar'),
  ('Cubiertos x24 Compacto Chico', 'Essen', 'Cubiertos x24 compacto — línea Essen', 'Hogar'),
  ('Sartén Clásico Grande', 'Lumilagro', 'Sartén clásico — línea Lumilagro', 'Hogar'),
  ('Perchero Clásico Grande', 'Nadín', 'Perchero clásico — línea Nadín', 'Hogar'),
  ('Tazas x6 Deluxe Individual', 'Lumilagro', 'Tazas x6 deluxe — línea Lumilagro', 'Hogar'),
  ('Organizador Deluxe Individual', 'Alba', 'Organizador deluxe — línea Alba', 'Hogar'),
  ('Acolchado Moderno Individual', 'Essen', 'Acolchado moderno — línea Essen', 'Hogar'),
  ('Vajilla x12 Moderno Matrimonial', 'Essen', 'Vajilla x12 moderno — línea Essen', 'Hogar'),
  ('Perchero Compacto Grande', 'Stanley', 'Perchero compacto — línea Stanley', 'Hogar'),
  ('Organizador Clásico Individual', 'Piazza', 'Organizador clásico — línea Piazza', 'Hogar'),
  ('Silla Compacto Chico', 'Bariloche', 'Silla compacto — línea Bariloche', 'Hogar'),
  ('Cortina Deluxe Mediano', 'Essen', 'Cortina deluxe — línea Essen', 'Hogar'),
  ('Repasador Compacto Mediano', 'Stanley', 'Repasador compacto — línea Stanley', 'Hogar'),
  ('Sartén Moderno Mediano', 'Umco', 'Sartén moderno — línea Umco', 'Hogar'),
  ('Termo Moderno Grande', 'Vittal', 'Termo moderno — línea Vittal', 'Hogar'),
  ('Lámpara de Pie Compacto Matrimonial', 'Umco', 'Lámpara de Pie compacto — línea Umco', 'Hogar'),
  ('Organizador Deluxe Mediano', 'Nadín', 'Organizador deluxe — línea Nadín', 'Hogar'),
  ('Cortina Compacto Chico', 'Bariloche', 'Cortina compacto — línea Bariloche', 'Hogar'),
  ('Maceta Moderno Chico', 'Essen', 'Maceta moderno — línea Essen', 'Hogar'),
  ('Sillón Deluxe Chico', 'Essen', 'Sillón deluxe — línea Essen', 'Hogar'),
  ('Escoba Moderno Mediano', 'Essen', 'Escoba moderno — línea Essen', 'Hogar'),
  ('Vajilla x12 Clásico Individual', 'Essen', 'Vajilla x12 clásico — línea Essen', 'Hogar'),
  ('Cortina Clásico Grande', 'Essen', 'Cortina clásico — línea Essen', 'Hogar'),
  ('Sartén Deluxe Individual', 'Umco', 'Sartén deluxe — línea Umco', 'Hogar'),
  ('Espejo Deluxe Matrimonial', 'Alba', 'Espejo deluxe — línea Alba', 'Hogar'),
  ('Espejo Compacto Individual', 'Alba', 'Espejo compacto — línea Alba', 'Hogar'),
  ('Cubiertos x24 Clásico Individual', 'Basement', 'Cubiertos x24 clásico — línea Basement', 'Hogar'),
  ('Cubiertos x24 Premium Chico', 'Cannon', 'Cubiertos x24 premium — línea Cannon', 'Hogar'),
  ('Lámpara de Pie Moderno Matrimonial', 'Piazza', 'Lámpara de Pie moderno — línea Piazza', 'Hogar'),
  ('Sartén Premium Mediano', 'Lumilagro', 'Sartén premium — línea Lumilagro', 'Hogar'),
  ('Mesa Ratona Premium Chico', 'Umco', 'Mesa Ratona premium — línea Umco', 'Hogar'),
  ('Alfombra Moderno Chico', 'Nadín', 'Alfombra moderno — línea Nadín', 'Hogar'),
  ('Juego de Sábanas Clásico Chico', 'Lumilagro', 'Juego de Sábanas clásico — línea Lumilagro', 'Hogar'),
  ('Termo Clásico Matrimonial', 'Piazza', 'Termo clásico — línea Piazza', 'Hogar'),
  ('Organizador Premium Mediano', 'Essen', 'Organizador premium — línea Essen', 'Hogar'),
  ('Termo Moderno Chico', 'Vittal', 'Termo moderno — línea Vittal', 'Hogar'),
  ('Vasos x6 Premium Grande', 'Stanley', 'Vasos x6 premium — línea Stanley', 'Hogar'),
  ('Alfombra Deluxe Mediano', 'Piazza', 'Alfombra deluxe — línea Piazza', 'Hogar'),
  ('Espejo Compacto Matrimonial', 'Umco', 'Espejo compacto — línea Umco', 'Hogar'),
  ('Acolchado Deluxe Chico', 'Basement', 'Acolchado deluxe — línea Basement', 'Hogar'),
  ('Espejo Moderno Individual', 'Lumilagro', 'Espejo moderno — línea Lumilagro', 'Hogar'),
  ('Sillón Clásico Individual', 'Bariloche', 'Sillón clásico — línea Bariloche', 'Hogar'),
  ('Mesa Ratona Clásico Matrimonial', 'Umco', 'Mesa Ratona clásico — línea Umco', 'Hogar'),
  ('Cesto de Ropa Clásico Matrimonial', 'Cannon', 'Cesto de Ropa clásico — línea Cannon', 'Hogar'),
  ('Cubiertos x24 Clásico Mediano', 'Stanley', 'Cubiertos x24 clásico — línea Stanley', 'Hogar'),
  ('Termo Clásico Mediano', 'Umco', 'Termo clásico — línea Umco', 'Hogar'),
  ('Vasos x6 Deluxe Chico', 'Tramontina', 'Vasos x6 deluxe — línea Tramontina', 'Hogar'),
  ('Acolchado Clásico Grande', 'Tramontina', 'Acolchado clásico — línea Tramontina', 'Hogar'),
  ('Silla Deluxe Chico', 'Lumilagro', 'Silla deluxe — línea Lumilagro', 'Hogar'),
  ('Sartén Premium Matrimonial', 'Umco', 'Sartén premium — línea Umco', 'Hogar'),
  ('Vasos x6 Deluxe Mediano', 'Lumilagro', 'Vasos x6 deluxe — línea Lumilagro', 'Hogar'),
  ('Portarretratos Moderno Mediano', 'Stanley', 'Portarretratos moderno — línea Stanley', 'Hogar'),
  ('Alfombra Premium Grande', 'Umco', 'Alfombra premium — línea Umco', 'Hogar'),
  ('Maceta Deluxe Individual', 'Stanley', 'Maceta deluxe — línea Stanley', 'Hogar'),
  ('Espejo Clásico Mediano', 'Vittal', 'Espejo clásico — línea Vittal', 'Hogar'),
  ('Portarretratos Compacto Grande', 'Nadín', 'Portarretratos compacto — línea Nadín', 'Hogar')
) AS v(name, brand, description, category)
WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = v.name);

INSERT INTO products (name, brand, description, category, created_at, updated_at)
SELECT v.name, v.brand, v.description, v.category, NOW(), NOW()
FROM (VALUES
  ('Vasos x6 Moderno Matrimonial', 'Alba', 'Vasos x6 moderno — línea Alba', 'Hogar'),
  ('Tazas x6 Moderno Individual', 'Essen', 'Tazas x6 moderno — línea Essen', 'Hogar'),
  ('Portarretratos Deluxe Grande', 'Stanley', 'Portarretratos deluxe — línea Stanley', 'Hogar'),
  ('Portarretratos Deluxe Mediano', 'Bariloche', 'Portarretratos deluxe — línea Bariloche', 'Hogar'),
  ('Cubiertos x24 Clásico Matrimonial', 'Cannon', 'Cubiertos x24 clásico — línea Cannon', 'Hogar'),
  ('Acolchado Clásico Chico', 'Lumilagro', 'Acolchado clásico — línea Lumilagro', 'Hogar'),
  ('Silla Clásico Individual', 'Basement', 'Silla clásico — línea Basement', 'Hogar'),
  ('Silla Moderno Matrimonial', 'Bariloche', 'Silla moderno — línea Bariloche', 'Hogar'),
  ('Set de Ollas Deluxe Individual', 'Lumilagro', 'Set de Ollas deluxe — línea Lumilagro', 'Hogar'),
  ('Acolchado Premium Grande', 'Piazza', 'Acolchado premium — línea Piazza', 'Hogar'),
  ('Escoba Compacto Matrimonial', 'Cannon', 'Escoba compacto — línea Cannon', 'Hogar'),
  ('Organizador Deluxe Chico', 'Bariloche', 'Organizador deluxe — línea Bariloche', 'Hogar'),
  ('Tazas x6 Clásico Mediano', 'Essen', 'Tazas x6 clásico — línea Essen', 'Hogar'),
  ('Vasos x6 Premium Chico', 'Lumilagro', 'Vasos x6 premium — línea Lumilagro', 'Hogar'),
  ('Organizador Premium Individual', 'Alba', 'Organizador premium — línea Alba', 'Hogar'),
  ('Acolchado Clásico Matrimonial', 'Umco', 'Acolchado clásico — línea Umco', 'Hogar'),
  ('Vajilla x12 Compacto Mediano', 'Umco', 'Vajilla x12 compacto — línea Umco', 'Hogar'),
  ('Tazas x6 Premium Grande', 'Tramontina', 'Tazas x6 premium — línea Tramontina', 'Hogar'),
  ('Maceta Premium Individual', 'Stanley', 'Maceta premium — línea Stanley', 'Hogar'),
  ('Repasador Clásico Matrimonial', 'Basement', 'Repasador clásico — línea Basement', 'Hogar'),
  ('Perchero Premium Mediano', 'Essen', 'Perchero premium — línea Essen', 'Hogar'),
  ('Espejo Compacto Mediano', 'Basement', 'Espejo compacto — línea Basement', 'Hogar'),
  ('Tazas x6 Premium Chico', 'Vittal', 'Tazas x6 premium — línea Vittal', 'Hogar'),
  ('Sillón Compacto Mediano', 'Tramontina', 'Sillón compacto — línea Tramontina', 'Hogar'),
  ('Repasador Premium Grande', 'Basement', 'Repasador premium — línea Basement', 'Hogar'),
  ('Desengrasante Sensitive x4', 'Johnson''s', 'Desengrasante sensitive — línea Johnson''s', 'Limpieza'),
  ('Crema Corporal Aloe Vera x12', 'Magistral', 'Crema Corporal aloe vera — línea Magistral', 'Limpieza'),
  ('Cepillo de Dientes Clásico x12', 'Off', 'Cepillo de Dientes clásico — línea Off', 'Limpieza'),
  ('Detergente Family x4', 'Huggies', 'Detergente family — línea Huggies', 'Limpieza'),
  ('Pasta Dental Aloe Vera x12', 'Nívea', 'Pasta Dental aloe vera — línea Nívea', 'Limpieza'),
  ('Jabón en Polvo Family x4', 'Poett', 'Jabón en Polvo family — línea Poett', 'Limpieza'),
  ('Papel Higiénico Clásico 500ml', 'Elite', 'Papel Higiénico clásico — línea Elite', 'Limpieza'),
  ('Jabón de Tocador Sensitive x4', 'Pampers', 'Jabón de Tocador sensitive — línea Pampers', 'Limpieza'),
  ('Bolsas de Residuo Sensitive 500ml', 'Rexona', 'Bolsas de Residuo sensitive — línea Rexona', 'Limpieza'),
  ('Crema Corporal Family 900ml', 'Ala', 'Crema Corporal family — línea Ala', 'Limpieza'),
  ('Lustramuebles Antibacterial x12', 'Off', 'Lustramuebles antibacterial — línea Off', 'Limpieza'),
  ('Papel Higiénico Family x12', 'Off', 'Papel Higiénico family — línea Off', 'Limpieza'),
  ('Shampoo Antibacterial 500ml', 'Cif', 'Shampoo antibacterial — línea Cif', 'Limpieza'),
  ('Toallitas Húmedas Family 500ml', 'Raid', 'Toallitas Húmedas family — línea Raid', 'Limpieza'),
  ('Insecticida Family x12', 'Pantene', 'Insecticida family — línea Pantene', 'Limpieza'),
  ('Shampoo Aloe Vera 900ml', 'Glade', 'Shampoo aloe vera — línea Glade', 'Limpieza'),
  ('Papel Higiénico Sensitive 250ml', 'Kolynos', 'Papel Higiénico sensitive — línea Kolynos', 'Limpieza'),
  ('Servilletas Clásico 900ml', 'Pampers', 'Servilletas clásico — línea Pampers', 'Limpieza'),
  ('Desengrasante Aloe Vera x4', 'Poett', 'Desengrasante aloe vera — línea Poett', 'Limpieza'),
  ('Detergente Clásico x4', 'Rexona', 'Detergente clásico — línea Rexona', 'Limpieza'),
  ('Detergente Clásico 900ml', 'Glade', 'Detergente clásico — línea Glade', 'Limpieza'),
  ('Limpiador Multiuso Aloe Vera 500ml', 'Scott', 'Limpiador Multiuso aloe vera — línea Scott', 'Limpieza'),
  ('Cepillo de Dientes Aloe Vera 900ml', 'Colgate', 'Cepillo de Dientes aloe vera — línea Colgate', 'Limpieza'),
  ('Cepillo de Dientes Aloe Vera x12', 'Pantene', 'Cepillo de Dientes aloe vera — línea Pantene', 'Limpieza'),
  ('Lavandina Clásico 250ml', 'Ala', 'Lavandina clásico — línea Ala', 'Limpieza'),
  ('Perfume Aloe Vera 250ml', 'Sedal', 'Perfume aloe vera — línea Sedal', 'Limpieza'),
  ('Crema Corporal Family x4', 'Colgate', 'Crema Corporal family — línea Colgate', 'Limpieza'),
  ('Suavizante Sensitive x4', 'Nívea', 'Suavizante sensitive — línea Nívea', 'Limpieza'),
  ('Pañales Antibacterial 250ml', 'Skip', 'Pañales antibacterial — línea Skip', 'Limpieza'),
  ('Protector Solar Aloe Vera 500ml', 'Pantene', 'Protector Solar aloe vera — línea Pantene', 'Limpieza'),
  ('Rollo de Cocina Clásico 500ml', 'Ala', 'Rollo de Cocina clásico — línea Ala', 'Limpieza'),
  ('Cepillo de Dientes Family 250ml', 'Sussex', 'Cepillo de Dientes family — línea Sussex', 'Limpieza'),
  ('Rollo de Cocina Sensitive 500ml', 'Kolynos', 'Rollo de Cocina sensitive — línea Kolynos', 'Limpieza'),
  ('Suavizante Antibacterial 500ml', 'Off', 'Suavizante antibacterial — línea Off', 'Limpieza'),
  ('Acondicionador Clásico 500ml', 'Pantene', 'Acondicionador clásico — línea Pantene', 'Limpieza'),
  ('Limpiador Multiuso Aloe Vera x4', 'Off', 'Limpiador Multiuso aloe vera — línea Off', 'Limpieza'),
  ('Rollo de Cocina Aloe Vera x4', 'Raid', 'Rollo de Cocina aloe vera — línea Raid', 'Limpieza'),
  ('Limpiador Multiuso Sensitive 900ml', 'Dove', 'Limpiador Multiuso sensitive — línea Dove', 'Limpieza'),
  ('Ambientador Aloe Vera 900ml', 'Magistral', 'Ambientador aloe vera — línea Magistral', 'Limpieza'),
  ('Shampoo Sensitive 250ml', 'Colgate', 'Shampoo sensitive — línea Colgate', 'Limpieza'),
  ('Perfume Clásico 500ml', 'Kolynos', 'Perfume clásico — línea Kolynos', 'Limpieza'),
  ('Bolsas de Residuo Antibacterial 900ml', 'Magistral', 'Bolsas de Residuo antibacterial — línea Magistral', 'Limpieza'),
  ('Pasta Dental Clásico x4', 'Magistral', 'Pasta Dental clásico — línea Magistral', 'Limpieza'),
  ('Rollo de Cocina Sensitive x4', 'Off', 'Rollo de Cocina sensitive — línea Off', 'Limpieza'),
  ('Pañales Aloe Vera 900ml', 'Magistral', 'Pañales aloe vera — línea Magistral', 'Limpieza'),
  ('Shampoo Clásico 500ml', 'Glade', 'Shampoo clásico — línea Glade', 'Limpieza'),
  ('Desengrasante Clásico 250ml', 'Magistral', 'Desengrasante clásico — línea Magistral', 'Limpieza'),
  ('Acondicionador Family 500ml', 'Magistral', 'Acondicionador family — línea Magistral', 'Limpieza'),
  ('Shampoo Aloe Vera 500ml', 'Huggies', 'Shampoo aloe vera — línea Huggies', 'Limpieza'),
  ('Rollo de Cocina Aloe Vera x12', 'Kolynos', 'Rollo de Cocina aloe vera — línea Kolynos', 'Limpieza'),
  ('Pañales Clásico x12', 'Johnson''s', 'Pañales clásico — línea Johnson''s', 'Limpieza'),
  ('Shampoo Clásico x12', 'Cif', 'Shampoo clásico — línea Cif', 'Limpieza'),
  ('Pañales Aloe Vera 250ml', 'Magistral', 'Pañales aloe vera — línea Magistral', 'Limpieza'),
  ('Rollo de Cocina Aloe Vera 900ml', 'Kolynos', 'Rollo de Cocina aloe vera — línea Kolynos', 'Limpieza'),
  ('Limpiador Multiuso Antibacterial 500ml', 'Dove', 'Limpiador Multiuso antibacterial — línea Dove', 'Limpieza'),
  ('Limpiador Multiuso Clásico 250ml', 'Colgate', 'Limpiador Multiuso clásico — línea Colgate', 'Limpieza'),
  ('Jabón en Polvo Antibacterial 900ml', 'Raid', 'Jabón en Polvo antibacterial — línea Raid', 'Limpieza'),
  ('Rollo de Cocina Antibacterial 250ml', 'Sussex', 'Rollo de Cocina antibacterial — línea Sussex', 'Limpieza'),
  ('Ambientador Sensitive x12', 'Elite', 'Ambientador sensitive — línea Elite', 'Limpieza'),
  ('Detergente Family 900ml', 'Poett', 'Detergente family — línea Poett', 'Limpieza'),
  ('Toallitas Húmedas Sensitive 250ml', 'Pampers', 'Toallitas Húmedas sensitive — línea Pampers', 'Limpieza'),
  ('Acondicionador Sensitive x12', 'Pampers', 'Acondicionador sensitive — línea Pampers', 'Limpieza'),
  ('Lustramuebles Aloe Vera 900ml', 'Scott', 'Lustramuebles aloe vera — línea Scott', 'Limpieza'),
  ('Desodorante Aloe Vera 900ml', 'Scott', 'Desodorante aloe vera — línea Scott', 'Limpieza'),
  ('Insecticida Clásico 250ml', 'Sedal', 'Insecticida clásico — línea Sedal', 'Limpieza'),
  ('Pañales Clásico 900ml', 'Axe', 'Pañales clásico — línea Axe', 'Limpieza'),
  ('Toallitas Húmedas Clásico 250ml', 'Pampers', 'Toallitas Húmedas clásico — línea Pampers', 'Limpieza'),
  ('Crema Corporal Clásico 500ml', 'Raid', 'Crema Corporal clásico — línea Raid', 'Limpieza'),
  ('Lavandina Sensitive x12', 'Pantene', 'Lavandina sensitive — línea Pantene', 'Limpieza'),
  ('Lavandina Family 900ml', 'Magistral', 'Lavandina family — línea Magistral', 'Limpieza'),
  ('Insecticida Antibacterial 250ml', 'Scott', 'Insecticida antibacterial — línea Scott', 'Limpieza'),
  ('Shampoo Family x12', 'Ala', 'Shampoo family — línea Ala', 'Limpieza'),
  ('Jabón en Polvo Sensitive x4', 'Dove', 'Jabón en Polvo sensitive — línea Dove', 'Limpieza'),
  ('Suavizante Clásico 500ml', 'Off', 'Suavizante clásico — línea Off', 'Limpieza'),
  ('Perfume Aloe Vera 500ml', 'Elite', 'Perfume aloe vera — línea Elite', 'Limpieza')
) AS v(name, brand, description, category)
WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = v.name);

INSERT INTO products (name, brand, description, category, created_at, updated_at)
SELECT v.name, v.brand, v.description, v.category, NOW(), NOW()
FROM (VALUES
  ('Lustramuebles Aloe Vera 250ml', 'Rexona', 'Lustramuebles aloe vera — línea Rexona', 'Limpieza'),
  ('Lavandina Family x4', 'Axe', 'Lavandina family — línea Axe', 'Limpieza'),
  ('Suavizante Family 250ml', 'Rexona', 'Suavizante family — línea Rexona', 'Limpieza'),
  ('Servilletas Antibacterial 900ml', 'Dove', 'Servilletas antibacterial — línea Dove', 'Limpieza'),
  ('Jabón en Polvo Aloe Vera x4', 'Skip', 'Jabón en Polvo aloe vera — línea Skip', 'Limpieza'),
  ('Acondicionador Family 900ml', 'Pantene', 'Acondicionador family — línea Pantene', 'Limpieza'),
  ('Servilletas Antibacterial 250ml', 'Pantene', 'Servilletas antibacterial — línea Pantene', 'Limpieza'),
  ('Pasta Dental Clásico 900ml', 'Huggies', 'Pasta Dental clásico — línea Huggies', 'Limpieza'),
  ('Jabón en Polvo Family 900ml', 'Nívea', 'Jabón en Polvo family — línea Nívea', 'Limpieza'),
  ('Perfume Clásico x4', 'Glade', 'Perfume clásico — línea Glade', 'Limpieza'),
  ('Pasta Dental Family x12', 'Nívea', 'Pasta Dental family — línea Nívea', 'Limpieza'),
  ('Protector Solar Aloe Vera x4', 'Rexona', 'Protector Solar aloe vera — línea Rexona', 'Limpieza'),
  ('Esponja Sensitive x4', 'Skip', 'Esponja sensitive — línea Skip', 'Limpieza'),
  ('Bolsas de Residuo Family x4', 'Scott', 'Bolsas de Residuo family — línea Scott', 'Limpieza'),
  ('Crema Corporal Aloe Vera 500ml', 'Pantene', 'Crema Corporal aloe vera — línea Pantene', 'Limpieza'),
  ('Toallitas Húmedas Antibacterial 250ml', 'Skip', 'Toallitas Húmedas antibacterial — línea Skip', 'Limpieza'),
  ('Lustramuebles Antibacterial 250ml', 'Nívea', 'Lustramuebles antibacterial — línea Nívea', 'Limpieza'),
  ('Rollo de Cocina Sensitive 900ml', 'Skip', 'Rollo de Cocina sensitive — línea Skip', 'Limpieza'),
  ('Rollo de Cocina Antibacterial 500ml', 'Rexona', 'Rollo de Cocina antibacterial — línea Rexona', 'Limpieza'),
  ('Jabón de Tocador Family 500ml', 'Colgate', 'Jabón de Tocador family — línea Colgate', 'Limpieza'),
  ('Lustramuebles Clásico 900ml', 'Colgate', 'Lustramuebles clásico — línea Colgate', 'Limpieza'),
  ('Lavandina Family x12', 'Dove', 'Lavandina family — línea Dove', 'Limpieza'),
  ('Bolsas de Residuo Aloe Vera 900ml', 'Skip', 'Bolsas de Residuo aloe vera — línea Skip', 'Limpieza'),
  ('Toallitas Húmedas Antibacterial x12', 'Magistral', 'Toallitas Húmedas antibacterial — línea Magistral', 'Limpieza'),
  ('Insecticida Clásico x12', 'Raid', 'Insecticida clásico — línea Raid', 'Limpieza'),
  ('Rollo de Cocina Family x12', 'Nívea', 'Rollo de Cocina family — línea Nívea', 'Limpieza'),
  ('Pañales Family 250ml', 'Huggies', 'Pañales family — línea Huggies', 'Limpieza'),
  ('Crema Corporal Sensitive x4', 'Glade', 'Crema Corporal sensitive — línea Glade', 'Limpieza'),
  ('Esponja Family 500ml', 'Pantene', 'Esponja family — línea Pantene', 'Limpieza'),
  ('Toallitas Húmedas Sensitive x4', 'Rexona', 'Toallitas Húmedas sensitive — línea Rexona', 'Limpieza'),
  ('Desengrasante Antibacterial x12', 'Rexona', 'Desengrasante antibacterial — línea Rexona', 'Limpieza'),
  ('Jabón de Tocador Family x4', 'Glade', 'Jabón de Tocador family — línea Glade', 'Limpieza'),
  ('Cepillo de Dientes Family x12', 'Rexona', 'Cepillo de Dientes family — línea Rexona', 'Limpieza'),
  ('Cepillo de Dientes Family 900ml', 'Kolynos', 'Cepillo de Dientes family — línea Kolynos', 'Limpieza'),
  ('Lavandina Antibacterial x12', 'Glade', 'Lavandina antibacterial — línea Glade', 'Limpieza'),
  ('Toallitas Húmedas Family x4', 'Glade', 'Toallitas Húmedas family — línea Glade', 'Limpieza'),
  ('Desodorante Clásico x4', 'Ayudín', 'Desodorante clásico — línea Ayudín', 'Limpieza'),
  ('Toallitas Húmedas Family x12', 'Rexona', 'Toallitas Húmedas family — línea Rexona', 'Limpieza'),
  ('Limpiador Multiuso Sensitive x4', 'Ayudín', 'Limpiador Multiuso sensitive — línea Ayudín', 'Limpieza'),
  ('Protector Solar Family x12', 'Pantene', 'Protector Solar family — línea Pantene', 'Limpieza'),
  ('Papel Higiénico Aloe Vera 900ml', 'Nívea', 'Papel Higiénico aloe vera — línea Nívea', 'Limpieza'),
  ('Insecticida Family x4', 'Poett', 'Insecticida family — línea Poett', 'Limpieza'),
  ('Pañales Sensitive 500ml', 'Pantene', 'Pañales sensitive — línea Pantene', 'Limpieza'),
  ('Desodorante Antibacterial 250ml', 'Poett', 'Desodorante antibacterial — línea Poett', 'Limpieza'),
  ('Detergente Aloe Vera 250ml', 'Huggies', 'Detergente aloe vera — línea Huggies', 'Limpieza'),
  ('Desodorante Sensitive x4', 'Magistral', 'Desodorante sensitive — línea Magistral', 'Limpieza'),
  ('Pasta Dental Aloe Vera x4', 'Magistral', 'Pasta Dental aloe vera — línea Magistral', 'Limpieza'),
  ('Suavizante Clásico x4', 'Glade', 'Suavizante clásico — línea Glade', 'Limpieza'),
  ('Pasta Dental Sensitive x12', 'Colgate', 'Pasta Dental sensitive — línea Colgate', 'Limpieza'),
  ('Limpiador Multiuso Clásico x12', 'Rexona', 'Limpiador Multiuso clásico — línea Rexona', 'Limpieza'),
  ('Transportadora Raza Grande 3kg', 'Royal Canin', 'Transportadora raza grande — línea Royal Canin', 'Mascotas'),
  ('Cama para Mascota Adulto 3kg', 'Purina', 'Cama para Mascota adulto — línea Purina', 'Mascotas'),
  ('Collar Adulto 3kg', 'Whiskas', 'Collar adulto — línea Whiskas', 'Mascotas'),
  ('Collar Raza Pequeña 15kg', 'Vitalcan', 'Collar raza pequeña — línea Vitalcan', 'Mascotas'),
  ('Transportadora Adulto 15kg', 'Pro Plan', 'Transportadora adulto — línea Pro Plan', 'Mascotas'),
  ('Antipulgas Raza Pequeña 7.5kg', 'Ricocan', 'Antipulgas raza pequeña — línea Ricocan', 'Mascotas'),
  ('Vitaminas para Mascota Adulto 15kg', 'Royal Canin', 'Vitaminas para Mascota adulto — línea Royal Canin', 'Mascotas'),
  ('Antipulgas Raza Grande 21kg', 'Pro Plan', 'Antipulgas raza grande — línea Pro Plan', 'Mascotas'),
  ('Cama para Mascota Adulto 15kg', 'Excellent', 'Cama para Mascota adulto — línea Excellent', 'Mascotas'),
  ('Juguete para Perro Raza Grande 7.5kg', 'Whiskas', 'Juguete para Perro raza grande — línea Whiskas', 'Mascotas'),
  ('Correa Adulto 21kg', 'Ricocan', 'Correa adulto — línea Ricocan', 'Mascotas'),
  ('Alimento Balanceado Gato Raza Grande 3kg', 'Excellent', 'Alimento Balanceado Gato raza grande — línea Excellent', 'Mascotas'),
  ('Juguete para Gato Cachorro 7.5kg', 'Gati', 'Juguete para Gato cachorro — línea Gati', 'Mascotas'),
  ('Comedero Raza Grande 21kg', 'Whiskas', 'Comedero raza grande — línea Whiskas', 'Mascotas'),
  ('Collar Cachorro 3kg', 'Purina', 'Collar cachorro — línea Purina', 'Mascotas'),
  ('Juguete para Gato Raza Pequeña 7.5kg', 'Gati', 'Juguete para Gato raza pequeña — línea Gati', 'Mascotas'),
  ('Cama para Mascota Raza Pequeña 7.5kg', 'Purina', 'Cama para Mascota raza pequeña — línea Purina', 'Mascotas'),
  ('Bebedero Raza Pequeña 21kg', 'Pro Plan', 'Bebedero raza pequeña — línea Pro Plan', 'Mascotas'),
  ('Alimento Balanceado Gato Cachorro 7.5kg', 'Excellent', 'Alimento Balanceado Gato cachorro — línea Excellent', 'Mascotas'),
  ('Cama para Mascota Senior 3kg', 'Pro Plan', 'Cama para Mascota senior — línea Pro Plan', 'Mascotas'),
  ('Vitaminas para Mascota Senior 7.5kg', 'Gati', 'Vitaminas para Mascota senior — línea Gati', 'Mascotas'),
  ('Juguete para Perro Senior 3kg', 'Cat Chow', 'Juguete para Perro senior — línea Cat Chow', 'Mascotas'),
  ('Alimento Balanceado Perro Raza Pequeña 7.5kg', 'Gati', 'Alimento Balanceado Perro raza pequeña — línea Gati', 'Mascotas'),
  ('Correa Cachorro 7.5kg', 'Excellent', 'Correa cachorro — línea Excellent', 'Mascotas'),
  ('Correa Senior 21kg', 'Old Prince', 'Correa senior — línea Old Prince', 'Mascotas'),
  ('Snacks para Perro Senior 15kg', 'Ricocan', 'Snacks para Perro senior — línea Ricocan', 'Mascotas'),
  ('Alimento Balanceado Gato Adulto 7.5kg', 'Royal Canin', 'Alimento Balanceado Gato adulto — línea Royal Canin', 'Mascotas'),
  ('Comedero Raza Pequeña 7.5kg', 'Purina', 'Comedero raza pequeña — línea Purina', 'Mascotas'),
  ('Snacks para Perro Senior 21kg', 'Pedigree', 'Snacks para Perro senior — línea Pedigree', 'Mascotas'),
  ('Antipulgas Adulto 1kg', 'Royal Canin', 'Antipulgas adulto — línea Royal Canin', 'Mascotas'),
  ('Juguete para Perro Cachorro 3kg', 'Pedigree', 'Juguete para Perro cachorro — línea Pedigree', 'Mascotas'),
  ('Juguete para Perro Adulto 7.5kg', 'Old Prince', 'Juguete para Perro adulto — línea Old Prince', 'Mascotas'),
  ('Alimento Balanceado Gato Senior 7.5kg', 'Cat Chow', 'Alimento Balanceado Gato senior — línea Cat Chow', 'Mascotas'),
  ('Vitaminas para Mascota Adulto 1kg', 'Dog Chow', 'Vitaminas para Mascota adulto — línea Dog Chow', 'Mascotas'),
  ('Bebedero Raza Grande 15kg', 'Ricocan', 'Bebedero raza grande — línea Ricocan', 'Mascotas'),
  ('Snacks para Perro Senior 3kg', 'Old Prince', 'Snacks para Perro senior — línea Old Prince', 'Mascotas'),
  ('Juguete para Perro Senior 21kg', 'Excellent', 'Juguete para Perro senior — línea Excellent', 'Mascotas'),
  ('Arena Sanitaria Raza Pequeña 15kg', 'Royal Canin', 'Arena Sanitaria raza pequeña — línea Royal Canin', 'Mascotas'),
  ('Juguete para Perro Raza Grande 1kg', 'Purina', 'Juguete para Perro raza grande — línea Purina', 'Mascotas'),
  ('Correa Cachorro 1kg', 'Dog Chow', 'Correa cachorro — línea Dog Chow', 'Mascotas'),
  ('Shampoo para Mascota Cachorro 21kg', 'Old Prince', 'Shampoo para Mascota cachorro — línea Old Prince', 'Mascotas'),
  ('Correa Senior 7.5kg', 'Purina', 'Correa senior — línea Purina', 'Mascotas'),
  ('Arena Sanitaria Raza Grande 7.5kg', 'Gati', 'Arena Sanitaria raza grande — línea Gati', 'Mascotas'),
  ('Antipulgas Cachorro 15kg', 'Pedigree', 'Antipulgas cachorro — línea Pedigree', 'Mascotas'),
  ('Juguete para Gato Raza Pequeña 3kg', 'Pedigree', 'Juguete para Gato raza pequeña — línea Pedigree', 'Mascotas'),
  ('Juguete para Perro Raza Pequeña 15kg', 'Pro Plan', 'Juguete para Perro raza pequeña — línea Pro Plan', 'Mascotas'),
  ('Snacks para Perro Raza Grande 7.5kg', 'Purina', 'Snacks para Perro raza grande — línea Purina', 'Mascotas'),
  ('Antipulgas Senior 1kg', 'Gati', 'Antipulgas senior — línea Gati', 'Mascotas'),
  ('Antipulgas Raza Grande 3kg', 'Pro Plan', 'Antipulgas raza grande — línea Pro Plan', 'Mascotas'),
  ('Correa Senior 1kg', 'Vitalcan', 'Correa senior — línea Vitalcan', 'Mascotas')
) AS v(name, brand, description, category)
WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = v.name);

INSERT INTO products (name, brand, description, category, created_at, updated_at)
SELECT v.name, v.brand, v.description, v.category, NOW(), NOW()
FROM (VALUES
  ('Cama para Mascota Senior 15kg', 'Excellent', 'Cama para Mascota senior — línea Excellent', 'Mascotas'),
  ('Vitaminas para Mascota Raza Grande 7.5kg', 'Pro Plan', 'Vitaminas para Mascota raza grande — línea Pro Plan', 'Mascotas'),
  ('Shampoo para Mascota Adulto 1kg', 'Royal Canin', 'Shampoo para Mascota adulto — línea Royal Canin', 'Mascotas'),
  ('Cama para Mascota Raza Pequeña 3kg', 'Excellent', 'Cama para Mascota raza pequeña — línea Excellent', 'Mascotas'),
  ('Cama para Mascota Raza Grande 3kg', 'Purina', 'Cama para Mascota raza grande — línea Purina', 'Mascotas'),
  ('Comedero Adulto 21kg', 'Pedigree', 'Comedero adulto — línea Pedigree', 'Mascotas'),
  ('Alimento Balanceado Gato Adulto 1kg', 'Vitalcan', 'Alimento Balanceado Gato adulto — línea Vitalcan', 'Mascotas'),
  ('Collar Raza Pequeña 3kg', 'Royal Canin', 'Collar raza pequeña — línea Royal Canin', 'Mascotas'),
  ('Cama para Mascota Cachorro 3kg', 'Royal Canin', 'Cama para Mascota cachorro — línea Royal Canin', 'Mascotas'),
  ('Antipulgas Adulto 15kg', 'Pedigree', 'Antipulgas adulto — línea Pedigree', 'Mascotas'),
  ('Alimento Balanceado Gato Raza Pequeña 3kg', 'Ricocan', 'Alimento Balanceado Gato raza pequeña — línea Ricocan', 'Mascotas'),
  ('Comedero Cachorro 1kg', 'Old Prince', 'Comedero cachorro — línea Old Prince', 'Mascotas'),
  ('Correa Raza Pequeña 3kg', 'Pro Plan', 'Correa raza pequeña — línea Pro Plan', 'Mascotas'),
  ('Snacks para Perro Adulto 15kg', 'Whiskas', 'Snacks para Perro adulto — línea Whiskas', 'Mascotas'),
  ('Comedero Adulto 7.5kg', 'Vitalcan', 'Comedero adulto — línea Vitalcan', 'Mascotas'),
  ('Correa Cachorro 21kg', 'Cat Chow', 'Correa cachorro — línea Cat Chow', 'Mascotas'),
  ('Arena Sanitaria Adulto 3kg', 'Whiskas', 'Arena Sanitaria adulto — línea Whiskas', 'Mascotas'),
  ('Arena Sanitaria Senior 15kg', 'Ricocan', 'Arena Sanitaria senior — línea Ricocan', 'Mascotas'),
  ('Snacks para Perro Adulto 21kg', 'Pro Plan', 'Snacks para Perro adulto — línea Pro Plan', 'Mascotas'),
  ('Alimento Balanceado Perro Senior 1kg', 'Gati', 'Alimento Balanceado Perro senior — línea Gati', 'Mascotas'),
  ('Cama para Mascota Cachorro 21kg', 'Whiskas', 'Cama para Mascota cachorro — línea Whiskas', 'Mascotas'),
  ('Bebedero Cachorro 7.5kg', 'Royal Canin', 'Bebedero cachorro — línea Royal Canin', 'Mascotas'),
  ('Juguete para Gato Senior 21kg', 'Cat Chow', 'Juguete para Gato senior — línea Cat Chow', 'Mascotas'),
  ('Antipulgas Senior 21kg', 'Old Prince', 'Antipulgas senior — línea Old Prince', 'Mascotas'),
  ('Alimento Balanceado Gato Raza Grande 1kg', 'Pedigree', 'Alimento Balanceado Gato raza grande — línea Pedigree', 'Mascotas'),
  ('Snacks para Perro Adulto 7.5kg', 'Royal Canin', 'Snacks para Perro adulto — línea Royal Canin', 'Mascotas'),
  ('Antipulgas Senior 15kg', 'Ricocan', 'Antipulgas senior — línea Ricocan', 'Mascotas'),
  ('Transportadora Senior 21kg', 'Excellent', 'Transportadora senior — línea Excellent', 'Mascotas'),
  ('Juguete para Gato Adulto 1kg', 'Cat Chow', 'Juguete para Gato adulto — línea Cat Chow', 'Mascotas'),
  ('Snacks para Perro Cachorro 1kg', 'Pedigree', 'Snacks para Perro cachorro — línea Pedigree', 'Mascotas'),
  ('Snacks para Perro Cachorro 21kg', 'Ricocan', 'Snacks para Perro cachorro — línea Ricocan', 'Mascotas'),
  ('Bebedero Senior 1kg', 'Vitalcan', 'Bebedero senior — línea Vitalcan', 'Mascotas'),
  ('Collar Senior 1kg', 'Cat Chow', 'Collar senior — línea Cat Chow', 'Mascotas'),
  ('Shampoo para Mascota Senior 3kg', 'Pro Plan', 'Shampoo para Mascota senior — línea Pro Plan', 'Mascotas'),
  ('Transportadora Senior 1kg', 'Ricocan', 'Transportadora senior — línea Ricocan', 'Mascotas'),
  ('Arena Sanitaria Senior 21kg', 'Cat Chow', 'Arena Sanitaria senior — línea Cat Chow', 'Mascotas'),
  ('Juguete para Gato Cachorro 3kg', 'Ricocan', 'Juguete para Gato cachorro — línea Ricocan', 'Mascotas'),
  ('Antipulgas Raza Grande 15kg', 'Pro Plan', 'Antipulgas raza grande — línea Pro Plan', 'Mascotas'),
  ('Juguete para Perro Raza Grande 15kg', 'Royal Canin', 'Juguete para Perro raza grande — línea Royal Canin', 'Mascotas'),
  ('Juguete para Perro Raza Pequeña 7.5kg', 'Cat Chow', 'Juguete para Perro raza pequeña — línea Cat Chow', 'Mascotas'),
  ('Correa Raza Grande 1kg', 'Ricocan', 'Correa raza grande — línea Ricocan', 'Mascotas'),
  ('Vitaminas para Mascota Senior 15kg', 'Cat Chow', 'Vitaminas para Mascota senior — línea Cat Chow', 'Mascotas'),
  ('Alimento Balanceado Gato Raza Pequeña 15kg', 'Whiskas', 'Alimento Balanceado Gato raza pequeña — línea Whiskas', 'Mascotas'),
  ('Juguete para Perro Adulto 15kg', 'Ricocan', 'Juguete para Perro adulto — línea Ricocan', 'Mascotas'),
  ('Shampoo para Mascota Raza Pequeña 1kg', 'Gati', 'Shampoo para Mascota raza pequeña — línea Gati', 'Mascotas'),
  ('Vitaminas para Mascota Adulto 7.5kg', 'Purina', 'Vitaminas para Mascota adulto — línea Purina', 'Mascotas'),
  ('Alimento Balanceado Perro Raza Grande 3kg', 'Vitalcan', 'Alimento Balanceado Perro raza grande — línea Vitalcan', 'Mascotas'),
  ('Alimento Balanceado Gato Adulto 3kg', 'Purina', 'Alimento Balanceado Gato adulto — línea Purina', 'Mascotas'),
  ('Snacks para Perro Raza Grande 15kg', 'Pedigree', 'Snacks para Perro raza grande — línea Pedigree', 'Mascotas'),
  ('Antipulgas Raza Grande 7.5kg', 'Whiskas', 'Antipulgas raza grande — línea Whiskas', 'Mascotas'),
  ('Juguete para Perro Raza Grande 21kg', 'Ricocan', 'Juguete para Perro raza grande — línea Ricocan', 'Mascotas'),
  ('Bebedero Raza Grande 1kg', 'Purina', 'Bebedero raza grande — línea Purina', 'Mascotas'),
  ('Juguete para Gato Senior 1kg', 'Excellent', 'Juguete para Gato senior — línea Excellent', 'Mascotas'),
  ('Shampoo para Mascota Adulto 3kg', 'Dog Chow', 'Shampoo para Mascota adulto — línea Dog Chow', 'Mascotas'),
  ('Snacks para Perro Raza Grande 1kg', 'Vitalcan', 'Snacks para Perro raza grande — línea Vitalcan', 'Mascotas'),
  ('Comedero Raza Grande 7.5kg', 'Dog Chow', 'Comedero raza grande — línea Dog Chow', 'Mascotas'),
  ('Transportadora Senior 3kg', 'Old Prince', 'Transportadora senior — línea Old Prince', 'Mascotas'),
  ('Juguete para Gato Adulto 3kg', 'Cat Chow', 'Juguete para Gato adulto — línea Cat Chow', 'Mascotas'),
  ('Alimento Balanceado Perro Senior 15kg', 'Whiskas', 'Alimento Balanceado Perro senior — línea Whiskas', 'Mascotas'),
  ('Snacks para Perro Raza Pequeña 1kg', 'Pro Plan', 'Snacks para Perro raza pequeña — línea Pro Plan', 'Mascotas'),
  ('Shampoo para Mascota Raza Grande 21kg', 'Cat Chow', 'Shampoo para Mascota raza grande — línea Cat Chow', 'Mascotas'),
  ('Transportadora Adulto 3kg', 'Royal Canin', 'Transportadora adulto — línea Royal Canin', 'Mascotas'),
  ('Transportadora Cachorro 3kg', 'Gati', 'Transportadora cachorro — línea Gati', 'Mascotas'),
  ('Vitaminas para Mascota Raza Pequeña 3kg', 'Pro Plan', 'Vitaminas para Mascota raza pequeña — línea Pro Plan', 'Mascotas'),
  ('Correa Raza Grande 21kg', 'Royal Canin', 'Correa raza grande — línea Royal Canin', 'Mascotas'),
  ('Alimento Balanceado Perro Raza Grande 1kg', 'Pedigree', 'Alimento Balanceado Perro raza grande — línea Pedigree', 'Mascotas'),
  ('Alimento Balanceado Perro Raza Pequeña 21kg', 'Pro Plan', 'Alimento Balanceado Perro raza pequeña — línea Pro Plan', 'Mascotas'),
  ('Vitaminas para Mascota Cachorro 7.5kg', 'Old Prince', 'Vitaminas para Mascota cachorro — línea Old Prince', 'Mascotas'),
  ('Alimento Balanceado Perro Raza Pequeña 1kg', 'Gati', 'Alimento Balanceado Perro raza pequeña — línea Gati', 'Mascotas'),
  ('Juguete para Perro Raza Pequeña 3kg', 'Whiskas', 'Juguete para Perro raza pequeña — línea Whiskas', 'Mascotas'),
  ('Snacks para Perro Adulto 3kg', 'Gati', 'Snacks para Perro adulto — línea Gati', 'Mascotas'),
  ('Arena Sanitaria Raza Grande 15kg', 'Excellent', 'Arena Sanitaria raza grande — línea Excellent', 'Mascotas'),
  ('Vitaminas para Mascota Cachorro 3kg', 'Gati', 'Vitaminas para Mascota cachorro — línea Gati', 'Mascotas'),
  ('Bebedero Cachorro 1kg', 'Old Prince', 'Bebedero cachorro — línea Old Prince', 'Mascotas'),
  ('Alimento Balanceado Gato Senior 1kg', 'Whiskas', 'Alimento Balanceado Gato senior — línea Whiskas', 'Mascotas'),
  ('Set de Cuchillos Clásico 1L', 'Longvie', 'Set de Cuchillos clásico — línea Longvie', 'Bazar'),
  ('Espumadera Multifunción Chico', 'Tramontina', 'Espumadera multifunción — línea Tramontina', 'Bazar'),
  ('Kit de Repostería Compacto Grande', 'Philco', 'Kit de Repostería compacto — línea Philco', 'Bazar'),
  ('Pava Eléctrica Multifunción Grande', 'Essen', 'Pava Eléctrica multifunción — línea Essen', 'Bazar'),
  ('Recipiente Hermético Premium Grande', 'Moulinex', 'Recipiente Hermético premium — línea Moulinex', 'Bazar'),
  ('Kit de Repostería Compacto 1L', 'Philco', 'Kit de Repostería compacto — línea Philco', 'Bazar'),
  ('Exprimidor Compacto 2L', 'Atma', 'Exprimidor compacto — línea Atma', 'Bazar'),
  ('Licuadora Clásico Mediano', 'Atma', 'Licuadora clásico — línea Atma', 'Bazar'),
  ('Recipiente Hermético Profesional Grande', 'Liliana', 'Recipiente Hermético profesional — línea Liliana', 'Bazar'),
  ('Tabla de Picar Multifunción 1L', 'Philco', 'Tabla de Picar multifunción — línea Philco', 'Bazar'),
  ('Molde para Torta Compacto Chico', 'Essen', 'Molde para Torta compacto — línea Essen', 'Bazar'),
  ('Pava Eléctrica Premium Chico', 'Longvie', 'Pava Eléctrica premium — línea Longvie', 'Bazar'),
  ('Molde para Torta Profesional Grande', 'Liliana', 'Molde para Torta profesional — línea Liliana', 'Bazar'),
  ('Cucharón Premium 1L', 'Liliana', 'Cucharón premium — línea Liliana', 'Bazar'),
  ('Tostadora Premium Grande', 'Ultracomb', 'Tostadora premium — línea Ultracomb', 'Bazar'),
  ('Balanza de Cocina Profesional 2L', 'Oster', 'Balanza de Cocina profesional — línea Oster', 'Bazar'),
  ('Kit de Repostería Clásico 2L', 'Essen', 'Kit de Repostería clásico — línea Essen', 'Bazar'),
  ('Batidora Clásico 2L', 'Moulinex', 'Batidora clásico — línea Moulinex', 'Bazar'),
  ('Sanguichera Profesional 1L', 'Atma', 'Sanguichera profesional — línea Atma', 'Bazar'),
  ('Molde para Torta Clásico Chico', 'Moulinex', 'Molde para Torta clásico — línea Moulinex', 'Bazar'),
  ('Tostadora Profesional 1L', 'Atma', 'Tostadora profesional — línea Atma', 'Bazar'),
  ('Horno Eléctrico Compacto 1L', 'Moulinex', 'Horno Eléctrico compacto — línea Moulinex', 'Bazar'),
  ('Tabla de Picar Compacto 2L', 'Essen', 'Tabla de Picar compacto — línea Essen', 'Bazar'),
  ('Espumadera Clásico Grande', 'Moulinex', 'Espumadera clásico — línea Moulinex', 'Bazar'),
  ('Balanza de Cocina Clásico 2L', 'Oster', 'Balanza de Cocina clásico — línea Oster', 'Bazar')
) AS v(name, brand, description, category)
WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = v.name);

INSERT INTO products (name, brand, description, category, created_at, updated_at)
SELECT v.name, v.brand, v.description, v.category, NOW(), NOW()
FROM (VALUES
  ('Colador Clásico 1L', 'Ultracomb', 'Colador clásico — línea Ultracomb', 'Bazar'),
  ('Espumadera Premium Grande', 'Essen', 'Espumadera premium — línea Essen', 'Bazar'),
  ('Colador Premium Grande', 'Ultracomb', 'Colador premium — línea Ultracomb', 'Bazar'),
  ('Sanguichera Profesional Grande', 'Peabody', 'Sanguichera profesional — línea Peabody', 'Bazar'),
  ('Procesadora Premium Grande', 'Liliana', 'Procesadora premium — línea Liliana', 'Bazar'),
  ('Espumadera Premium 1L', 'Tramontina', 'Espumadera premium — línea Tramontina', 'Bazar'),
  ('Balanza de Cocina Compacto Mediano', 'Atma', 'Balanza de Cocina compacto — línea Atma', 'Bazar'),
  ('Cucharón Profesional Grande', 'Moulinex', 'Cucharón profesional — línea Moulinex', 'Bazar'),
  ('Anafe Eléctrico Compacto Chico', 'Moulinex', 'Anafe Eléctrico compacto — línea Moulinex', 'Bazar'),
  ('Pava Eléctrica Profesional Mediano', 'Tramontina', 'Pava Eléctrica profesional — línea Tramontina', 'Bazar'),
  ('Horno Eléctrico Premium Mediano', 'Essen', 'Horno Eléctrico premium — línea Essen', 'Bazar'),
  ('Licuadora Compacto 2L', 'Liliana', 'Licuadora compacto — línea Liliana', 'Bazar'),
  ('Molde para Torta Multifunción Chico', 'Atma', 'Molde para Torta multifunción — línea Atma', 'Bazar'),
  ('Cucharón Premium Chico', 'Oster', 'Cucharón premium — línea Oster', 'Bazar'),
  ('Tostadora Clásico 2L', 'Philco', 'Tostadora clásico — línea Philco', 'Bazar'),
  ('Horno Eléctrico Clásico Grande', 'Atma', 'Horno Eléctrico clásico — línea Atma', 'Bazar'),
  ('Tostadora Premium 2L', 'Moulinex', 'Tostadora premium — línea Moulinex', 'Bazar'),
  ('Batidora Clásico Mediano', 'Longvie', 'Batidora clásico — línea Longvie', 'Bazar'),
  ('Recipiente Hermético Compacto 1L', 'Ultracomb', 'Recipiente Hermético compacto — línea Ultracomb', 'Bazar'),
  ('Batidora Clásico Chico', 'Ultracomb', 'Batidora clásico — línea Ultracomb', 'Bazar'),
  ('Kit de Repostería Profesional Chico', 'Philco', 'Kit de Repostería profesional — línea Philco', 'Bazar'),
  ('Set de Cuchillos Premium Chico', 'Tramontina', 'Set de Cuchillos premium — línea Tramontina', 'Bazar'),
  ('Recipiente Hermético Premium 1L', 'Ultracomb', 'Recipiente Hermético premium — línea Ultracomb', 'Bazar'),
  ('Recipiente Hermético Premium Chico', 'Peabody', 'Recipiente Hermético premium — línea Peabody', 'Bazar'),
  ('Horno Eléctrico Compacto Mediano', 'Peabody', 'Horno Eléctrico compacto — línea Peabody', 'Bazar'),
  ('Espumadera Clásico Chico', 'Ultracomb', 'Espumadera clásico — línea Ultracomb', 'Bazar'),
  ('Licuadora Profesional 2L', 'Peabody', 'Licuadora profesional — línea Peabody', 'Bazar'),
  ('Licuadora Profesional Chico', 'Peabody', 'Licuadora profesional — línea Peabody', 'Bazar'),
  ('Tabla de Picar Profesional 1L', 'Essen', 'Tabla de Picar profesional — línea Essen', 'Bazar'),
  ('Termómetro de Cocina Multifunción 1L', 'Philco', 'Termómetro de Cocina multifunción — línea Philco', 'Bazar'),
  ('Licuadora Multifunción Mediano', 'Moulinex', 'Licuadora multifunción — línea Moulinex', 'Bazar'),
  ('Molde para Torta Multifunción 2L', 'Peabody', 'Molde para Torta multifunción — línea Peabody', 'Bazar'),
  ('Batidora Compacto 2L', 'Tramontina', 'Batidora compacto — línea Tramontina', 'Bazar'),
  ('Colador Clásico 2L', 'Philco', 'Colador clásico — línea Philco', 'Bazar'),
  ('Espumadera Compacto Grande', 'Moulinex', 'Espumadera compacto — línea Moulinex', 'Bazar'),
  ('Tostadora Compacto 2L', 'Peabody', 'Tostadora compacto — línea Peabody', 'Bazar'),
  ('Set de Cuchillos Clásico Grande', 'Essen', 'Set de Cuchillos clásico — línea Essen', 'Bazar'),
  ('Tostadora Compacto 1L', 'Oster', 'Tostadora compacto — línea Oster', 'Bazar'),
  ('Molde para Torta Premium Mediano', 'Peabody', 'Molde para Torta premium — línea Peabody', 'Bazar'),
  ('Rallador Multifunción Chico', 'Philco', 'Rallador multifunción — línea Philco', 'Bazar'),
  ('Colador Multifunción 1L', 'Atma', 'Colador multifunción — línea Atma', 'Bazar'),
  ('Batidora Multifunción Chico', 'Philco', 'Batidora multifunción — línea Philco', 'Bazar'),
  ('Termómetro de Cocina Compacto Chico', 'Ultracomb', 'Termómetro de Cocina compacto — línea Ultracomb', 'Bazar'),
  ('Tostadora Premium Chico', 'Ultracomb', 'Tostadora premium — línea Ultracomb', 'Bazar'),
  ('Espumadera Compacto 1L', 'Longvie', 'Espumadera compacto — línea Longvie', 'Bazar'),
  ('Sanguichera Multifunción Mediano', 'Longvie', 'Sanguichera multifunción — línea Longvie', 'Bazar'),
  ('Cucharón Profesional Mediano', 'Moulinex', 'Cucharón profesional — línea Moulinex', 'Bazar'),
  ('Colador Premium Chico', 'Essen', 'Colador premium — línea Essen', 'Bazar'),
  ('Balanza de Cocina Multifunción Chico', 'Tramontina', 'Balanza de Cocina multifunción — línea Tramontina', 'Bazar'),
  ('Licuadora Clásico Chico', 'Atma', 'Licuadora clásico — línea Atma', 'Bazar'),
  ('Balanza de Cocina Clásico Chico', 'Tramontina', 'Balanza de Cocina clásico — línea Tramontina', 'Bazar'),
  ('Exprimidor Clásico Chico', 'Liliana', 'Exprimidor clásico — línea Liliana', 'Bazar'),
  ('Kit de Repostería Premium 1L', 'Essen', 'Kit de Repostería premium — línea Essen', 'Bazar'),
  ('Kit de Repostería Profesional Mediano', 'Longvie', 'Kit de Repostería profesional — línea Longvie', 'Bazar'),
  ('Tostadora Profesional 2L', 'Longvie', 'Tostadora profesional — línea Longvie', 'Bazar'),
  ('Termómetro de Cocina Clásico Chico', 'Ultracomb', 'Termómetro de Cocina clásico — línea Ultracomb', 'Bazar'),
  ('Licuadora Premium 2L', 'Essen', 'Licuadora premium — línea Essen', 'Bazar'),
  ('Horno Eléctrico Profesional Chico', 'Moulinex', 'Horno Eléctrico profesional — línea Moulinex', 'Bazar'),
  ('Kit de Repostería Multifunción Mediano', 'Essen', 'Kit de Repostería multifunción — línea Essen', 'Bazar'),
  ('Batidora Compacto Chico', 'Oster', 'Batidora compacto — línea Oster', 'Bazar'),
  ('Batidora Premium Grande', 'Philco', 'Batidora premium — línea Philco', 'Bazar'),
  ('Balanza de Cocina Profesional Mediano', 'Atma', 'Balanza de Cocina profesional — línea Atma', 'Bazar'),
  ('Colador Compacto Grande', 'Philco', 'Colador compacto — línea Philco', 'Bazar'),
  ('Exprimidor Premium Chico', 'Oster', 'Exprimidor premium — línea Oster', 'Bazar'),
  ('Colador Profesional Grande', 'Philco', 'Colador profesional — línea Philco', 'Bazar'),
  ('Exprimidor Profesional Grande', 'Philco', 'Exprimidor profesional — línea Philco', 'Bazar'),
  ('Pava Eléctrica Multifunción 1L', 'Moulinex', 'Pava Eléctrica multifunción — línea Moulinex', 'Bazar'),
  ('Anafe Eléctrico Multifunción Grande', 'Essen', 'Anafe Eléctrico multifunción — línea Essen', 'Bazar'),
  ('Tostadora Multifunción Mediano', 'Moulinex', 'Tostadora multifunción — línea Moulinex', 'Bazar'),
  ('Horno Eléctrico Profesional Grande', 'Oster', 'Horno Eléctrico profesional — línea Oster', 'Bazar'),
  ('Recipiente Hermético Profesional 2L', 'Ultracomb', 'Recipiente Hermético profesional — línea Ultracomb', 'Bazar'),
  ('Set de Cuchillos Compacto 2L', 'Oster', 'Set de Cuchillos compacto — línea Oster', 'Bazar'),
  ('Pava Eléctrica Premium 1L', 'Oster', 'Pava Eléctrica premium — línea Oster', 'Bazar'),
  ('Rallador Profesional Chico', 'Longvie', 'Rallador profesional — línea Longvie', 'Bazar'),
  ('Licuadora Multifunción Grande', 'Peabody', 'Licuadora multifunción — línea Peabody', 'Bazar'),
  ('Procesadora Profesional 2L', 'Moulinex', 'Procesadora profesional — línea Moulinex', 'Bazar'),
  ('Sanguichera Profesional Mediano', 'Atma', 'Sanguichera profesional — línea Atma', 'Bazar'),
  ('Pava Eléctrica Clásico 2L', 'Essen', 'Pava Eléctrica clásico — línea Essen', 'Bazar'),
  ('Sanguichera Premium 2L', 'Longvie', 'Sanguichera premium — línea Longvie', 'Bazar'),
  ('Rallador Premium Chico', 'Essen', 'Rallador premium — línea Essen', 'Bazar'),
  ('Colador Compacto Chico', 'Ultracomb', 'Colador compacto — línea Ultracomb', 'Bazar'),
  ('Pava Eléctrica Compacto 1L', 'Atma', 'Pava Eléctrica compacto — línea Atma', 'Bazar'),
  ('Licuadora Multifunción 2L', 'Longvie', 'Licuadora multifunción — línea Longvie', 'Bazar'),
  ('Balanza de Cocina Profesional Chico', 'Peabody', 'Balanza de Cocina profesional — línea Peabody', 'Bazar'),
  ('Exprimidor Profesional Mediano', 'Oster', 'Exprimidor profesional — línea Oster', 'Bazar'),
  ('Molde para Torta Premium 1L', 'Moulinex', 'Molde para Torta premium — línea Moulinex', 'Bazar'),
  ('Procesadora Clásico 2L', 'Ultracomb', 'Procesadora clásico — línea Ultracomb', 'Bazar'),
  ('Kit de Repostería Premium 2L', 'Ultracomb', 'Kit de Repostería premium — línea Ultracomb', 'Bazar'),
  ('Molde para Torta Profesional 2L', 'Moulinex', 'Molde para Torta profesional — línea Moulinex', 'Bazar'),
  ('Procesadora Premium 2L', 'Tramontina', 'Procesadora premium — línea Tramontina', 'Bazar'),
  ('Cucharón Premium 2L', 'Ultracomb', 'Cucharón premium — línea Ultracomb', 'Bazar'),
  ('Rallador Compacto Chico', 'Moulinex', 'Rallador compacto — línea Moulinex', 'Bazar'),
  ('Balanza de Cocina Clásico 1L', 'Ultracomb', 'Balanza de Cocina clásico — línea Ultracomb', 'Bazar'),
  ('Tabla de Picar Clásico Grande', 'Moulinex', 'Tabla de Picar clásico — línea Moulinex', 'Bazar'),
  ('Licuadora Premium 1L', 'Liliana', 'Licuadora premium — línea Liliana', 'Bazar'),
  ('Colador Multifunción Mediano', 'Ultracomb', 'Colador multifunción — línea Ultracomb', 'Bazar'),
  ('Pava Eléctrica Multifunción Chico', 'Essen', 'Pava Eléctrica multifunción — línea Essen', 'Bazar'),
  ('Kit de Repostería Clásico Chico', 'Philco', 'Kit de Repostería clásico — línea Philco', 'Bazar'),
  ('Pava Eléctrica Premium Grande', 'Longvie', 'Pava Eléctrica premium — línea Longvie', 'Bazar'),
  ('Recipiente Hermético Multifunción 2L', 'Ultracomb', 'Recipiente Hermético multifunción — línea Ultracomb', 'Bazar')
) AS v(name, brand, description, category)
WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = v.name);

